### ISSUE TITLE
Overwatch-Bot Killed

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#100]
Hi I start and I get the error below, receive on pc and vps (ubuntu), a solution something or is it from me?
![vps2](https://user-images.githubusercontent.com/45514952/91659449-4504cf00-ead8-11ea-9053-b72ea3ca8401.png)
![vps](https://user-images.githubusercontent.com/45514952/91659450-4635fc00-ead8-11ea-9832-60a3aaffd952.png)

**Comment by BeepIsla** [comment]
I assume you ran out of memory. Have any NodeJS logs generated in the folder?

**Comment by xSuspect** [comment]
> I assume you ran out of memory. Have any NodeJS logs generated in the folder?

on vps where you have to find them(vps spec 1 gb ram 2 core, on version 1owb, it didn't stop)

**Comment by BeepIsla** [comment]
This is a different version. It could be related to the new bot no longer actively writing to disk and rather keeping everything in memory until its finished being used. It shouldn't take up a lot though.

Look in `/var/log/syslog` and check for any NodeJS processes being killed.

**Comment by xSuspect** [comment]
I can give it to you privately, I don't want to make it public ?

**Comment by BeepIsla** [comment]
No. Just open the file I mentioned and check the logs. It will probably just say something like `Out of memory: Kill process 29620 (nodejs)`

**Comment by xSuspect** [comment]
I didn't take a picture like a few logs
![ssarfwsef](https://user-images.githubusercontent.com/45514952/91659895-5ac7c380-eadb-11ea-9d50-1f86e91acc8c.png)

**Comment by BeepIsla** [comment]
Just search `nodejs`

**Comment by xSuspect** [comment]
> nodejs

![aeqaeqweqr](https://user-images.githubusercontent.com/45514952/91659954-b09c6b80-eadb-11ea-941e-29abfbc77121.png)
![srfwerwerwr](https://user-images.githubusercontent.com/45514952/91659957-b1350200-eadb-11ea-9304-ac5d8e3dd6be.png)

**Comment by BeepIsla** [comment]
Open two connections to the server, on one run `htop` on the other one run the bot and see how high your memory goes.

**Comment by xSuspect** [comment]
yes it is possible when it downloads the demo and unzips it the branch goes up to 100% and stops but I don't even have vps to run in the background
![stop](https://user-images.githubusercontent.com/45514952/91660223-ba26d300-eadd-11ea-9c99-52b61be638d2.png)
![run 1](https://user-images.githubusercontent.com/45514952/91660225-babf6980-eadd-11ea-8953-4c6fc29b4d99.png)

**Comment by BeepIsla** [comment]
The problem just seems to be your low RAM.
