### ISSUE TITLE
INSTANT solve and only Griefing

### ISSUE THREAD

**Issue by alprutxd** [BeepIsla/CSGO-Overwatch-Bot#101]
Yo, Since I got the new version it instans solves the case and only reports for griefing 
![OWbot](https://user-images.githubusercontent.com/42916890/91661498-20fbba80-eae5-11ea-93b4-7b35095e8d0a.PNG)

**Comment by BeepIsla** [comment]
Download the demo and watch it manually

**Comment by alprutxd** [comment]
Okay, its still instant (Was not in old version), but now it reported for Aimbot, Wallhack and Griefing

**Comment by BeepIsla** [comment]
So the Overwatch bot itself running on an account and `force.js` output different results? What is the demo and suspect?

**Comment by alprutxd** [comment]
Im not saving demos since I have to pay more for my VPS, so I only got x amount of GB

**Comment by alprutxd** [comment]
![billede](https://user-images.githubusercontent.com/42916890/91661900-894b9b80-eae7-11ea-9ed8-e6f0b03c526a.png)
IDK, if this can help

**Comment by BeepIsla** [comment]
Copy Suspect & Download URL and paste them here

**Comment by alprutxd** [comment]
Suspect : 76561199085923161
Download URL: http://replay186.valve.net/730/003433243476697809333_0390309868.dem.bz2

**Comment by alprutxd** [comment]
dont know if it gotta be .dem or .demo

**Comment by alprutxd** [comment]
dont know if it gotta be .dem or .demo

**Comment by BeepIsla** [comment]
That download link does not work, make sure you copy the whole thing, or for comparison screenshot your command prompt in full

**Comment by alprutxd** [comment]
![billede](https://user-images.githubusercontent.com/42916890/91662008-62da3000-eae8-11ea-9ffc-f89907cecaa8.png)

**Comment by alprutxd** [comment]
Can't copy from my VPS

**Comment by BeepIsla** [comment]
This is the download URL: http://replay241.valve.net/730/003433313400912871628_0390800521.dem.bz2

**Comment by alprutxd** [comment]
And now I use force.js?

**Comment by BeepIsla** [comment]
Download it, unzip it, and play it in CSGO. Watch the suspect and see if the verdict the bot is making is correct.

It doesn't matter if the bot takes 3 seconds to analyze the whole demo or not.

**Comment by alprutxd** [comment]
okay :) will try

**Comment by BeepIsla** [comment]
For me `force.js` outputs:

```
Infrations:
        -   AFKing:   1
        -   Aimbot: 113
        -  AntiAim:   3
        - Griefing:   0
        - Wallhack:  21
Verdict:
        -   Aimbot: ✔️
        - Wallhack: ✔️
        -    Other: ❌
        - Griefing: ❌
```

**Comment by alprutxd** [comment]
yeah looks right

**Comment by alprutxd** [comment]
Im going into CS now

**Comment by alprutxd** [comment]
Seems to be working
