### ISSUE TITLE
steam error

### ISSUE THREAD

**Issue by Andyzer4** [BeepIsla/CSGO-Overwatch-Bot#105]
Waiting 4:37 minutes before sending verdict...
Sending verdict to CSGO...
Finished doing 1 verdict
Disconnected from Steam with EResult 3 and message NoConnection

**Comment by Chartone** [comment]
For me too, I am getting the same error!

**Comment by Chartone** [comment]
https://prnt.sc/u8p5hq

**Comment by DarkVader-cell** [comment]
https://github.com/BeepIsla/CSGO-Overwatch-Bot/issues/87

**Comment by BeepIsla** [comment]
Duplicate #87. Read the README.
