### ISSUE TITLE
''Disconnected from Steam with EResult 3 and message NoConnection''

### ISSUE THREAD

**Issue by joshua641** [BeepIsla/CSGO-Overwatch-Bot#107]
I´m having this problem: ''Disconnected from Steam with EResult 3 and message NoConnection''. After the bot finish a case, this message appears and I have to do the index process all over again. Can i do just one case at a time?

**Comment by BeepIsla** [comment]
Read the README. This is the 5th duplicate issue, it has already been answered and is clearly explained in the README. #87

**Comment by joshua641** [comment]
thank u bro. You re insane!!!
