### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/CSGO-Overwatch-Bot#110]
https://prnt.sc/u96wjv

Why it stops everytime after the first case ???

My config:
{
	"account": {
		"username": "*****************",
		"password": "******************",
		"sharedSecret": ""
	},
	"parsing": {
		"forceConvictOnPreviousBan": 3,
		"minimumTime": 240,
		"aimbot": {
			"maxTicks": 10,
			"threshold": 1.0
		},
		"afking": {
			"radius": 50
		}
	},
	"detectors": {
		"Aimbot": true,
		"Wallhack": true,
		"Griefing": true,
		"AFKing": true,
		"AntiAim": true
	},
	"verdict": {
		"writeLog": true,
		"backupDemo": true,
		"printScoreboard": true,
		"logWithEmojis": true,
		"maxVerdicts": 1,

		"minAimbot": 10,
		"minWallKills": 5,
		"minAFKing": 5,
		"minAntiAim": 10,
		"minTeamKills": 2,
		"minTeamDamage": 150
	}
}

**Comment by BeepIsla** [comment]
Read. The. Readme. #87
