### ISSUE TITLE
Counter of how many OW

### ISSUE THREAD

**Issue by code-bye** [BeepIsla/CSGO-Overwatch-Bot#111]
Would you be able to add the old counter of how many OW demos were made?
In the past your bot had this counter and I would like to know how many OWs I had already done, if possible could I add it again for this new version?
It would be really cool if you added a more detailed option example:
- total OW done (adding all folders would give you the total)
and the total OW done in the last session

**Comment by BeepIsla** [comment]
> total OW done (adding all folders would give you the total)

Open the `cases` folder and look at how many folders there are in it. Every OS should have a counter itself.

**Comment by BeepIsla** [comment]
Added
