### ISSUE TITLE
One more error

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/CSGO-Overwatch-Bot#112]
https://prnt.sc/u9df00

It happens after the first verdict after i put 0 for unlimited verdicts , and the bot gets stuck sometimes.

{
	"account": {
		"username": "-----",
		"password": "------",
		"sharedSecret": ""
	},
	"parsing": {
		"forceConvictOnPreviousBan": 3,
		"minimumTime": 240,
		"aimbot": {
			"maxTicks": 10,
			"threshold": 1.0
		},
		"afking": {
			"radius": 50
		}
	},
	"detectors": {
		"Aimbot": true,
		"Wallhack": true,
		"Griefing": true,
		"AFKing": true,
		"AntiAim": true
	},
	"verdict": {
		"writeLog": true,
		"backupDemo": true,
		"printScoreboard": true,
		"logWithEmojis": true,
		"maxVerdicts": 0,

		"minAimbot": 10,
		"minWallKills": 5,
		"minAFKing": 5,
		"minAntiAim": 10,
		"minTeamKills": 2,
		"minTeamDamage": 150
	}
}

**Comment by BeepIsla** [comment]
Something cause the bot to Disconnect. Maybe you starting a game on the same account or just a bad internet connection.

**Comment by Musta40** [comment]
I have downloaded new version yesterday, it was working fine, but today after steam update overwatch bot not working? Is there any solution? Can i download from somewhere older version like 3-4 weeks old, that version still works :) thanks

**Comment by dezeadmf** [comment]
> I have downloaded new version yesterday, it was working fine, but today after steam update overwatch bot not working? Is there any solution? Can i download from somewhere older version like 3-4 weeks old, that version still works :) thanks

The bot is working fine for me. It's a problem on your end. Be sure to run the bot without Steam open

**Comment by BeepIsla** [comment]
> Can i download from somewhere older version like 3-4 weeks old, that version still works :) thanks

All changes are stored and saved. You can go to any version of the bot. Just click on the one you want [here](https://github.com/BeepIsla/CSGO-Overwatch-Bot/commits/master) and then click `Browse Files` in the top right.

---

As this problem seems to be unique to you and  there doesn't seem to be a solution I will close it. If someone **else** has the same problem comment here.
