### ISSUE TITLE
Disconnected from Steam with EResult 3 and message NoConnection

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#113]
the same message on vps and pc
![Screenshot_1](https://user-images.githubusercontent.com/45514952/91898702-c90bb200-eca4-11ea-9bb6-3fb7e14a1254.png)

**Comment by BeepIsla** [comment]
Something is causing the connection to break or you are starting a game on your account which kicks out the bot.

**Comment by BeepIsla** [comment]
Actually I read it again. You have to actually **read**. You have to be Gold Nova 1 or above. You are unranked.

**Comment by xSuspect** [comment]
> Actually I read it again. You have to actually **read**. You have to be Gold Nova 1 or above. You are unranked.

I have "supreme first class" on my account, but I took party member ban and shook a match, and the "bot" didn't realize the rank of why I have to play a match data you manage, to check directly whether you now or not, but not out of rank

**Comment by BeepIsla** [comment]
No rank = No Overwach

**Comment by xSuspect** [comment]
sorry for the inconvenience now I noticed
