### ISSUE TITLE
F2p/Prime Skip possible?

### ISSUE THREAD

**Issue by code-bye** [BeepIsla/CSGO-Overwatch-Bot#114]
Hello @BeepIsla , I have a great suggestion for you, it would be nice and very useful to clean up the community if the bot could recognize primes and non primes (f2p) accounts.
example: if the account is free (skip the OW if possible or else despite doing a force conviction) so we would only analyze the prime players who really are the ones who damage the game with their sh1t cheaters.

**Why am I asking for this?**
This is simple I do OW practically all day on 4 accounts and practically 90% of the demos analyzed are from newly created accounts this is ridiculous (the valve does not send primes players to OW with priority so they are almost never banned)

**Comment by BeepIsla** [comment]
I will never add any kind of force conviction.
