### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by AdVIAnAS** [BeepIsla/CSGO-Overwatch-Bot#116]
Allow us to hide our online/ingame status

**Comment by KeinNameVorhanden** [comment]
In addition: If the persona is set to offline, getting the rank will sometime fail.
Doesn't happen with the older version.

`steam.setPersona(SteamUser.EPersonaState.Offline);`

**Comment by AdVIAnAS** [comment]
> 
> 
> In addition: If the persona is set to offline, getting the rank will sometime fail.
> Doesn't happen with the older version.
> 
> `steam.setPersona(SteamUser.EPersonaState.Offline);`

`steam.setPersona(SteamUser.EPersonaState.Invisible);` seems to be working for me
