### ISSUE TITLE
Display game played?

### ISSUE THREAD

**Issue by LegendNed** [BeepIsla/CSGO-Overwatch-Bot#117]
Unsure if an issue or intensional, whenever using the `bot` it doesn't display that I'm really playing CS GO, is there something id need to change or no?

**Comment by BeepIsla** [comment]
What do you mean? What does it say? Screenshot?

**Comment by LegendNed** [comment]
> What do you mean? What does it say? Screenshot?

Unsure what type of screenshots to provide, however, when running the `bot` it doesn't display that you are playing cs go on steam, it just shows that you are online that's all.

**Comment by BeepIsla** [comment]
That should not happen and does not happen to me. If the bit is not shown as playing CSGO it won't be able to communicate with the CSGO Backend. Are you sure the bot is running and not exiting due to either finishing the amount of cases wanted (As per config) or exiting due to rank/wins?

**Comment by LegendNed** [comment]
The funny part is, it shows that I'm just `Online` not showing I'm `playing cs go`, however, it's communicating with cs go servers without an issue, able to do cases with no issue (no exits etc). Just strangely `gamesPlayed` doesn't set my game played as `CS GO`.

**Comment by BeepIsla** [comment]
Are you logged into Steam when viewing your Steam profile? If not are you hiding your game details?

**Comment by LegendNed** [comment]
Attempted to test this with my account being logged in and logged out to check if it's running. Additionally, I do not hide the steam library games I currently play. 

Just find it strange that it works like my account is playing `CS GO` just doesn't display on my profile that I am.

Furthermore, I just noticed that I am running `steam-user 4.17.1` version, however, that should effect the `gamesPlayed` (correct?).

**Comment by BeepIsla** [comment]
Nothing changed in how the game you are playing is being sent to Steam for years.

What does it show here? https://steamcommunity.com/dev/testrichpresence

**Comment by LegendNed** [comment]
As expected :D
https://img.dustie.xyz/qPel

**Comment by BeepIsla** [comment]
That makes no sense. As said if the bot is not in-game it cannot communicate with the CSGO Network. There must be a problem on your side, looking at the wrong account or something.

**Comment by LegendNed** [comment]
> That makes no sense. As said if the bot is not in-game it cannot communicate with the CSGO Network. There must be a problem on your side, looking at the wrong account or something.

I guess we should close this as there is no true answer, it is the right account, it's communicating perfectly as its doing overwatch cases. Just confused why o-o
