### ISSUE TITLE
Steam connection loss during parsing

### ISSUE THREAD

**Issue by huraken77** [BeepIsla/CSGO-Overwatch-Bot#118]
Its on a Linux server (Ubuntu 20.04.1 LTS \n \l)

Parsing: 0%events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: NoConnection
    at SteamUser._handleLogOff (/root/CSGO-Overwatch-Bot-master/node_modules/steam-user/components/logon.js:544:11)
    at SteamUser._handleConnectionClose (/root/CSGO-Overwatch-Bot-master/node_modules/steam-user/components/connection.js:17:8)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
Emitted 'error' event on SteamUser instance at:
    at SteamUser._handleLogOff (/root/CSGO-Overwatch-Bot-master/node_modules/steam-user/components/logon.js:551:8)
    at SteamUser._handleConnectionClose (/root/CSGO-Overwatch-Bot-master/node_modules/steam-user/components/connection.js:17:8)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12) {
  eresult: 3
}

**Comment by BeepIsla** [comment]
Bot loses connection to Steam while parsing for some reason. That's all info I can gather from this.

**Comment by huraken77** [comment]
i saw that too but idk why maybe because its on a linux server ? should i open any ports or something ?

**Comment by BeepIsla** [comment]
No ports required, OS doesn't matter

**Comment by huraken77** [comment]
do you have any idea how i can fix it ?

**Comment by BeepIsla** [comment]
Maybe its thread blocking, in other words parsing one action took too long and it was unable to keep Steam connection up. As NodeJS can only do one thing at at time.

**Comment by huraken77** [comment]
https://prnt.sc/uci1o1 when i force parse it its working

**Comment by BeepIsla** [comment]
Because when using force.js there is no Steam connection

**Comment by huraken77** [comment]
its working on some demos but not on every now its demo dependent

**Comment by xSuspect** [comment]
@BeepIsla so do I
![Screenshot_1](https://user-images.githubusercontent.com/45514952/92960922-1511e000-f477-11ea-9ec3-285cd6203eae.png)
![Screenshot_2](https://user-images.githubusercontent.com/45514952/92960925-16430d00-f477-11ea-9471-c4220aa50b4b.png)
![Screenshot_3](https://user-images.githubusercontent.com/45514952/92960926-16dba380-f477-11ea-91e9-134f308a1bcf.png)

**Comment by BeepIsla** [comment]
Please downloading the new [worker branch](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) and test if you still experience the same issues.

This new branch uses a separate worker thread to parse the demo so the main thread is not blocked and Steam connection can continue like normal. If you no longer run into the connection loss issue for a few days please confirm it by commenting or reacting to this message.

**Comment by xSuspect** [comment]
> Please downloading the new [worker branch](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) and test if you still experience the same issues.
> 
> This new branch uses a separate worker thread to parse the demo so the main thread is not blocked and Steam connection can continue like normal. If you no longer run into the connection loss issue for a few days please confirm it by commenting or reacting to this message.

I will test one day, 2 and I will come up with an answer.

**Comment by xSuspect** [comment]
@BeepIsla Worker 
![Screenshot_1](https://user-images.githubusercontent.com/45514952/93003363-c895d580-f546-11ea-9df1-229473a4d203.png)

**Comment by xSuspect** [comment]
what I put above does so at every demo  v-->Worker

**Comment by tempestuz** [comment]
Sending verdict to CSGO...
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: NoConnection
    at SteamUser._handleLogOff (C:\Users\Tempe\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\logon.js:544:11)
    at SteamUser._handleConnectionClose (C:\Users\Tempe\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\connection.js:17:8)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:672:12)
Emitted 'error' event on SteamUser instance at:
    at SteamUser._handleLogOff (C:\Users\Tempe\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\logon.js:551:8)
    at SteamUser._handleConnectionClose (C:\Users\Tempe\Desktop\CSGO-Overwatch-Bot-master\node_modules\steam-user\components\connection.js:17:8)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:672:12) {
  eresult: 3
}

**Comment by BeepIsla** [comment]
@xSuspect If you can try the [`worker` branch](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) again, it has been updated to include all of the latest changes from `master` and some more. Maybe it helps with memory usage?

**Comment by xSuspect** [comment]
> @xSuspect If you can try the [`worker` branch](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) again, it has been updated to include all of the latest changes from `master` and some more. Maybe it helps with memory usage?

I'm sure, I'll give you an answer tomorrow, I'll leave it on tonight

**Comment by xSuspect** [comment]
@BeepIsla 
I tested now, and still receive ram increases 3.80- 4 gb, the stable version works perfectly, but you get connection time out
![te](https://user-images.githubusercontent.com/45514952/93717608-88a2a400-fb7f-11ea-9ee0-beaf86cda4b6.png)

**Comment by BeepIsla** [comment]
Related to this #139
