### ISSUE TITLE
The bot isn't accurate at all !!

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/CSGO-Overwatch-Bot#119]
I tried to make an ow case using the bot , and these are the results : https://prnt.sc/ucwy2k

after that I've watched the demo , I saw that he is walling , shooting throw wall , aim bot etc...

and the bot did not report that guy !!

Can you fix this by updating the detectors ?

**Comment by SwissFuse** [comment]
edit your config to report on lower occasions

**Comment by BeepIsla** [comment]
You should include a demo and your config (Censor account details)
