### ISSUE TITLE
Halt

### ISSUE THREAD

**Issue by LegendNed** [BeepIsla/CSGO-Overwatch-Bot#120]
The process becomes to a halt whenever there is a pending overwatch case aka `reason: undefined` and `verdict: 0`. Unsure if it's really a bug but overwatch bot doesn't start properly and doesn't return anything afterwards.

To reproduce this bug, just comment and I can edit this post. (Discovered it accidentally)

**Comment by BeepIsla** [comment]
https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/b8d8c87280fd6f819130c7dadf3e1520dccf1bce/helpers/Helper.js#L17

https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/b8d8c87280fd6f819130c7dadf3e1520dccf1bce/index.js#L173-L175

According to this code above pending cases should get handled like normal.

**Comment by LegendNed** [comment]
I might be wrong with this as I was just scrolling through the code too, however I'm unsure how entirely I reproduced it but I have an idea. Once a case is complete and is waiting to be sent, forcefully quit the code and run it again. Meaning, it should receive the same case, however, unsure if it is bad of me being an idiot and missing that part out, but receiving undefined as reason and verdict as 0 made no changes/nothing was executed.

My bad if I am in correct.

**Comment by BeepIsla** [comment]
When a case is completed and verdict is sent a cooldown will be sent to you. I don't exactly know how a cooldown message looks like but I think it is handled correctly? I will take a look to verify.

**Comment by BeepIsla** [comment]
Starting the bot during an active cooldown indeed softlocks.
