### ISSUE TITLE
Latest Update

### ISSUE THREAD

**Issue by LegendNed** [BeepIsla/CSGO-Overwatch-Bot#121]
Latest update should have introduced something about the pending requests, however its faulty.

https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/8560c71f500155b2431467c735fe8db973a1f199/index.js#L446

Should be:
```js
body.verdict === Helper.OverwatchConstants.EMMV2OverwatchCasesVerdict_t.k_EMMV2OverwatchCasesVerdict_Pending &&
```

**Comment by BeepIsla** [comment]
According to what you said yes, but my test gave me this result:
![image](https://user-images.githubusercontent.com/22947557/92501949-7cbdf600-f1ff-11ea-9bd7-938b4bf9d2a9.png)

**Comment by LegendNed** [comment]
Strange I end up with different results, cause the code to be in a halt again if the fix mentioned was not applied.

https://img.dustie.xyz/cuAI

**Comment by BeepIsla** [comment]
This is just your case, when you get this the bot should just download the demo, parse it, and send the result back to Valve. All conditions are met as well:

- SuspectID
- CaseURL
- CaseID
- Reason doesn't exist
- Verdict is "Pending"

**Comment by LegendNed** [comment]
I will continue with this testing in 30 minutes after my rate limit ban is lifted.

**Comment by LegendNed** [comment]
Update:

Was unable to complete testing after `rateLimitExceeded` ban was lifted. However, it was an issue on my end, the verdict should be `undefined` after I was received a case caused by a `halt` (or whatever you'd want to call. Sorry!

Closing it
