### ISSUE TITLE
Emoji's (Green Check Mark and Red X) do not display

### ISSUE THREAD

**Issue by MRB055101** [BeepIsla/CSGO-Overwatch-Bot#125]
![image](https://user-images.githubusercontent.com/22947557/91612419-acf2d280-e97d-11ea-95fa-12d0b3b074bc.png)
(example of how it should look like)
_Originally posted by @BeepIsla in https://github.com/BeepIsla/CSGO-Overwatch-Bot/issues/90#issuecomment-683132710_

O wonder if this issue is on my side or part of something else because I keep getting [?][?]

**Comment by BeepIsla** [comment]
Whatever you are using to run the bot cannot handle emojis correctly. Either change it to something that can, upgrade your OS (If its old and doesn't have emoji support) or modify your config to disable emojis and use text instead.

**Comment by MRB055101** [comment]
I use Windows PowerShell so any recommendations?

**Comment by MRB055101** [comment]
> Whatever you are using to run the bot cannot handle emojis correctly. Either change it to something that can, upgrade your OS (If its old and doesn't have emoji support) or modify your config to disable emojis and use text instead.

I use Windows PowerShell so any recommendations?

**Comment by BeepIsla** [comment]
Try Command Prompt (`cmd`) instead

**Comment by MRB055101** [comment]
Ok

**Comment by MRB055101** [comment]
> Try Command Prompt (`cmd`) instead

How would I go about switching from Windows Powershell to CMD

**Comment by BeepIsla** [comment]
Open the folder with the overwatch bot where the index.js and config.json are located and click on [this area](https://helpdeskgeek.com/wp-content/pictures/2020/05/Program-Files.jpg.webp) then just type `cmd` and press enter

**Comment by MRB055101** [comment]
> Open the folder with the overwatch bot where the index.js and config.json are located and click on [this area](https://helpdeskgeek.com/wp-content/pictures/2020/05/Program-Files.jpg.webp) then just type `cmd` into it and press enter

Thank you very much
