### ISSUE TITLE
Little issue

### ISSUE THREAD

**Issue by jelia-cpu** [BeepIsla/CSGO-Overwatch-Bot#126]
Demos are not deleted. Demos take up my free space

**Comment by BeepIsla** [comment]
Turn off demo saving. The README explains the entire config...

> `writeLog`: Should we write our logs to a folder called `cases/<CaseID>`?
> `backupDemo`: Should we backup the Overwatch demo in a folder called `cases/<CaseID>`?

**Comment by jelia-cpu** [comment]
Omg thank you dear
Will you still update the bot? I love him

**Comment by BeepIsla** [comment]
Sometimes
