### ISSUE TITLE
Invisible mode not working

### ISSUE THREAD

**Issue by AdVIAnAS** [BeepIsla/CSGO-Overwatch-Bot#129]
I've set "invisible": true and it's still shows me online and ingame.

Also on another note: Can you save the login token when using 2FA so you don't have to reenter your Steam Guard Code everytime when you can't access your Shared Secret (iOS). I don't know how hard this is to implement but it works flawless in ArchiSteamFarm and I only have to enter my 2FA code every few weeks.

**Comment by BeepIsla** [comment]
> I've set "invisible": true and it's still shows me online and ingame

I know why, will fix soon

> Can you save the login token when using 2FA

I have no idea how exactly this works but I can take a look
