### ISSUE TITLE
Overwatch XP Reward question

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#132]
Hi, I saw that you put new things in this project, and I wanted to ask, how does it work more exactly? and what should I do if I find a bug?
Thank you for doing these projects for free, and good luck in the future.

**Comment by BeepIsla** [comment]
Changes are described in the CHANGELOG, The `config.json.example` is always up-to-date so just compare your old config with it.

Reporting bugs is just describing whats wrong ir not working, config, maybe example demo and I think NodeJS version.

There isn't much to it,.
