### ISSUE TITLE
Trouble

### ISSUE THREAD

**Issue by jelia-cpu** [BeepIsla/CSGO-Overwatch-Bot#134]
![image](https://user-images.githubusercontent.com/56301017/93284968-4418b080-f7ed-11ea-8c7e-94dd43284e06.png)
Not mine trouble idk what is it.

**Comment by BeepIsla** [comment]
Connectiom to Steam was lost, either your internet losing connection or Steam going offline.

**Comment by jelia-cpu** [comment]
Its not mine trouble lol

**Comment by BeepIsla** [comment]
If **you** don't have an issue then **don't** open one.
