### ISSUE TITLE
stuck here :- Checking for Overwatch access... 

### ISSUE THREAD

**Issue by ilovegame1985** [BeepIsla/CSGO-Overwatch-Bot#135]
Establishing CSGO GameCoordinator connection...
Established CSGO connection, getting rank information...
We are Master Guardian II with 301 wins
Checking for Overwatch access...

**Comment by BeepIsla** [comment]
Do you have access to Overwatch in-game?

**Comment by ilovegame1985** [comment]
yes sir 300 wins

**Comment by BeepIsla** [comment]
Did you start CSGO or any other game?

**Comment by ilovegame1985** [comment]
no i am on my another steam id 
today i get this issue

**Comment by BeepIsla** [comment]
Did it work before?

**Comment by ilovegame1985** [comment]
yes its work like charm

**Comment by ilovegame1985** [comment]
this id has competative cd

**Comment by BeepIsla** [comment]
Maybe that is the problem, I think you do not have Overwatch access while on cooldown.

**Comment by ilovegame1985** [comment]
oh ok
after 7 hrs if slove this problem i closed this topic 
thank you!

**Comment by ilovegame1985** [comment]
thanks problem solve after done my cd
