### ISSUE TITLE
(NoConnection) Thread blocked and Steam disconnecting when unpacking/parsing demo

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#139]
Today I received, and the first time  ~~<Cannot read property '0' of undefined>
[ http://replay233.wmsj.cn/730/003437111625176318317_1657434214.dem.bz2]~~
NoConnection I receive almost every day
![Screenshot_3](https://user-images.githubusercontent.com/45514952/93706110-c970cd80-fb2b-11ea-816a-25e88b30a51f.png)
![Screenshot_1](https://user-images.githubusercontent.com/45514952/93706111-cc6bbe00-fb2b-11ea-9af7-aedce22c7a0e.png)
![Screenshot_2](https://user-images.githubusercontent.com/45514952/93706113-ce358180-fb2b-11ea-9d50-e49c95f385a5.png)

**Comment by BeepIsla** [comment]
Something is causing the connection to Steam to just break. I don't know what it could be.

> Today I received, and the first time <Cannot read property '0' of undefined>

#30

**Comment by BeepIsla** [comment]
Please focus on Steam disconnecting when unpacking/parsing a demo here. My recent attempt at fixing this with a worker process failed but I will try again soon.

**Comment by xSuspect** [comment]
still persist, but I'm waiting for a solution 👍 
![Screenshot_1](https://user-images.githubusercontent.com/45514952/94338232-47841700-fff9-11ea-8f98-c2ba1c1b624b.png)

[http://replay233.wmsj.cn/730/003438299329662550180_1878992474.dem.bz2]

**Comment by BeepIsla** [comment]
Logging off after an error is on purpose. If you want the bot to reconnect use something like `pm2`, `foreverJS` or a linix `screen`.

**Comment by xSuspect** [comment]
> Logging off after an error is on purpose. If you want the bot to reconnect use something like `pm2`, `foreverJS` or a linux `screen`.

I'll try, but I also talked about data / loginkey which on vps [ubuntu] doesn't work on pc yes

**Comment by BeepIsla** [comment]
I don't know why it doesn't work, it should work the exact same on both OS

**Comment by BeepIsla** [comment]
Another try! Please download the new [worker](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) branch and try again.

Hopefully this solves RAM, Parsing & Unpacking issues.

**Comment by xSuspect** [comment]
works well, I tested on 10-15 cases, I'll leave it overnight, I still have to work on ram until (1.70, 2) but it works well, I will come tomorrow with a concrete answer, or you can publish it

**Comment by xSuspect** [comment]
> Another try! Please download the new [worker](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/worker) branch and try again.
> 
> Hopefully this solves RAM, Parsing & Unpacking issues.

works well, I tested on 10-15 cases, I'll leave it overnight, I still have to work on ram until (1.70, 2) but it works well, I will come tomorrow with a concrete answer, or you can publish it

**Comment by BeepIsla** [comment]
@xSuspect any update?

**Comment by xSuspect** [comment]
> update
works fine, you no longer receive this error, only occasionally no connection !

**Comment by BeepIsla** [comment]
Maybe from Steam maintenance?

**Comment by xSuspect** [comment]
possibly, you could publish it, either we steam or from vps

**Comment by BeepIsla** [comment]
Great, will push live later.

**Comment by BeepIsla** [comment]
Added in 2.6.2
