### ISSUE TITLE
Error: NoConnection

### ISSUE THREAD

**Issue by NoSpread** [BeepIsla/CSGO-Overwatch-Bot#141]
Seems like this issue is popping up more and more.
Any ideas? I can try to take care of it myself, but maybe you can make a guess first.

It's really weird because it seems to be working on my main pc, but not on my server, is Steam blocking something?
I tried on my raspi as well, but it crashes as well with the same error message, but I could guess it's a RAM issue. I have 2 GB Swap tho.
![69ae90b1561e51c5a8c03d4d152416e86db0dbc0](https://user-images.githubusercontent.com/20584206/93816534-f3bfa980-fc57-11ea-9a29-ea7ff3d5564c.png)

**Comment by NoSpread** [comment]
Really seems to be a ram issue, I tried on a different server and it seems to work flawlessly.

**Comment by BeepIsla** [comment]
CPU problem I think, single threaded. Unpacking or parsing takes the whole CPUs power. In that time it cannot ping Steam and if it takes too long Steam will disconnect.

**Comment by BeepIsla** [comment]
I tried solving this in the worker branch but it csused 4GB ram usage compares to the normal ~400 MB
