### ISSUE TITLE
data/loginKey not working!

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#142]
data/loginKey doesn't work, should it work like [sharedSecret]? because it doesn't connect I have to put steam guard every time, or when disconnecting from steam it does not auto connect !

**Comment by BeepIsla** [comment]
Just enable `saveSteamGuard`, that's it.

**Comment by Musta40** [comment]
How to enable this save steam guard?

**Comment by BeepIsla** [comment]
There is a [README](https://github.com/BeepIsla/CSGO-Overwatch-Bot/tree/b3fcf48e4a1471d334cdecf8b8551b20788a7d36#config) and an [example config](https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/b3fcf48e4a1471d334cdecf8b8551b20788a7d36/config.json.example#L6).

**Comment by xSuspect** [comment]
it really doesn't work,the first time it was introduced it doesn't work
![Screenshot_1](https://user-images.githubusercontent.com/45514952/94052760-0cf46180-fde2-11ea-8632-eaa82db999b5.png)
![Screenshot_2](https://user-images.githubusercontent.com/45514952/94052769-0ebe2500-fde2-11ea-8a31-75c28d635a39.png)

**Comment by BeepIsla** [comment]
Works fine for me, set `saveSteamGuard` to `true`, start the bot, enter Steam Guard one final time, done. Every time after that it automatically logs into the account without asking for Steam Guard.

It might not work for you because you are running multiple instances of the bot and the login key gets overridden by other accounts?

**Comment by xSuspect** [comment]
I will download this version again and I will try.

**Comment by xSuspect** [comment]
@BeepIsla in fact it doesn't work on vps but it works on windows, on vps it makes me put steam guard, yes I checked config
