### ISSUE TITLE
demo.suspectPlayer.Kills,assist,deaths

### ISSUE THREAD

**Issue by ninjaibiss** [BeepIsla/CSGO-Overwatch-Bot#148]
I tried to get the suspect kills, assist, death manually and console log it because I don't want to use log scoreboard 
because its buggy so I did it and it worked for like 10 overwatch in a row then it got like an error --
TypeError: Cannot read property 'kills' of undefined

**Comment by ninjaibiss** [comment]
can u like tell me why this is happening whenever an error occurs then it doesn't work

**Comment by BeepIsla** [comment]
1. There is existing code which gets all the data for you. Use it. https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/b3fcf48e4a1471d334cdecf8b8551b20788a7d36/helpers/Demo.js#L300-L328

2. The suspect probably left and this is why you are getting the error

3. If you modify the code you are on your own, **don't ask me**. Your modification, your responsibility to make it work. If you don't know enough, learn JavaScript and learn how to debug.
