### ISSUE TITLE
Check your internet connection

### ISSUE THREAD

**Issue by CrazieWolf19** [BeepIsla/CSGO-Overwatch-Bot#149]
I have used the bot to examine 3 OW and it stopped working showing the following error message

![image](https://user-images.githubusercontent.com/67511404/94468614-180d1000-019b-11eb-8bd0-593caaf8b8ae.png)

Does anyone know how to fix it?

**Comment by BeepIsla** [comment]
As it the error says, this happens when downloading fails. There isn't a lot of information logged, this isn't solvable with so little information. I will add more logging later.
