### ISSUE TITLE
Failed to find protobufs, downloading and extracting...

### ISSUE THREAD

**Issue by bROKENSHOT** [BeepIsla/CSGO-Overwatch-Bot#15]
PS C:\Users\Asus\Desktop\CSGO-Overwatch-Bot-master> node index.js
Steam Guard App Code: x5tmr
Successfully logged into 76561198203855996
Checking protobufs...
Failed to find protobufs, downloading and extracting...

**Comment by BeepIsla** [comment]
What happens afterwards? Does it just exit? Nothing more?

**Comment by BeepIsla** [comment]
The same issue was reported on my Commend Bot a while ago, I implemented the same fix. Hopefully it works.

Try it out and report back.

**Comment by bROKENSHOT** [comment]
itss work now Thank you

**Comment by vrajparesh** [comment]
![commend](https://user-images.githubusercontent.com/10117584/81143058-c0bd9780-8f8e-11ea-9a7e-bf80a5518516.PNG)


It is still ocurring
