### ISSUE TITLE
Steamworks

### ISSUE THREAD

**Issue by hammerx1337** [BeepIsla/CSGO-Overwatch-Bot#150]
Hello, this error appears when using the steamworks method, all additional node.js programs installed
![Снимок](https://user-images.githubusercontent.com/72270982/94946099-4fa1f200-04e4-11eb-816d-5e8787bc4dcc.PNG)

**Comment by BeepIsla** [comment]
What is your Operation System?

Are you using 32-Bit or 64-Bit?

Do you have the following folder structure?

- `data`
  - `win32`
    - `steam_api.dll`
  - `win64`
    - `steam_api64.dll`
  - `osx`
    - `libsteam_api.dylib`
  - `linux32`
    - `libsteam_api.so`
  - `linux64`
    - `libsteam_api.so`
- `index.js`
- *Other files and folders*

**Comment by hammerx1337** [comment]
I am using Windows 10 64-bit, the steam_api64.dll file is located in the folder under the path C: \ Users \ hamme_hchmvp8 \ OneDrive \ Desktop \ CSGO-Overwatch-Bot-master (2) \ CSGO-Overwatch-Bot-master \ extension \ steam \ sdk \ redistributable_bin \ win64

**Comment by BeepIsla** [comment]
It should be in the data folder under `data/win64/steam_api64.dll` as well?

**Comment by xSuspect** [comment]
a few errors
first I fixed (/home/csgo/data/linux64/*)
![Screenshot_1](https://user-images.githubusercontent.com/45514952/94991451-e5dd2300-058b-11eb-914b-35f027a57796.png)

the second must be installed again (`node-gyp`)?

![Screenshot_2](https://user-images.githubusercontent.com/45514952/94991501-40767f00-058c-11eb-82ca-757feee7dd79.png)

**Comment by BeepIsla** [comment]
@xSuspect read the README.

> You **must** have Steam running while using this.

You cannot run this on a VPS, you **need** the Steam client.

**Comment by xSuspect** [comment]
> @xSuspect read the README.
> 
> > You **must** have Steam running while using this.
> 
> You cannot run this on a VPS, you **need** the Steam client.

thanks, but if I install steam, and Steamworks is better than what standard for a vps?

**Comment by BeepIsla** [comment]
Doesn't really matter. Steamworks just allows you to easily run it without account details and while playing other games. While the normal version waits while you play other games. Neither can be used while playing CSGO. Steamworks **must** run on your computer with Steam, if you want 24/7 solving without running your PC all the time the normal version should work better.

**Comment by xSuspect** [comment]
I just installed it on windows, and I get these errors. I also reinstalled the node js and checked that box. the second link I think did not install visual studio properly
https://pastebin.com/raw/Ntdx6tia
https://pastebin.com/raw/YQ7BCNqM

**Comment by BeepIsla** [comment]
What Node version is that?

**Comment by xSuspect** [comment]
> What Node version is that?

*`node-v12.18.4-x64`*

**Comment by BeepIsla** [comment]
Try latest v14

**Comment by xSuspect** [comment]
> Try latest v14
I uninstalled `node-v12.18.4-x64` and after I installed `node-v14.13.0-x64`
and I get the error (I think it's from steamworks)
https://pastebin.com/N0XCMbK4

**Comment by BeepIsla** [comment]
Yes. Edit `extension/steam/binding.gyp` and change both `..` to just `.`.

Like this

```
"./sdk/redistributable_bin/steam_api.lib",
"../sdk/redistributable_bin/win64/steam_api64.lib",
```

**Comment by xSuspect** [comment]
> Yes. Edit `extension/steam/binding.gyp` and change both `..` to just `.`.
> 
> Like this
> 
> ```
> "./sdk/redistributable_bin/steam_api.lib",
> "./sdk/redistributable_bin/win64/steam_api64.lib",
> ```
> 
> then try again

same shit 
https://pastebin.com/GjkKaBPc
![Screenshot_1](https://user-images.githubusercontent.com/45514952/94993096-3a39d000-0597-11eb-9b2c-b5396c047b96.png)

**Comment by BeepIsla** [comment]
I know why, I have to fix it later
