### ISSUE TITLE
[QUESTION] Demo Info

### ISSUE THREAD

**Issue by BlackYuzia** [BeepIsla/CSGO-Overwatch-Bot#151]
You (**BeepIsla**) output info about players in table (kills, assists, wins, score, team, rank etc)
Question: **Valve has been write rank and count of wins info in to the demo?**
Question: **Where I can full list of info what I can find in the demo?**

Maybe something interest (and usable) we can find for output?

### Screenshot 

![image](https://user-images.githubusercontent.com/25010528/94991361-50419380-058b-11eb-892c-2e40d18721e3.png)

**Comment by BeepIsla** [comment]
> Valve has been write rank and count of wins info in to the demo?

Yes.

---

> Where I can full list of info what I can find in the demo?

- https://saul.github.io/demofile/classes/_demo_.demofile.html

- https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events

- https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_UserMessages

- Netprops (Can be dumped by downloading a CSGO server, installing [MetaMod](https://www.sourcemm.net/) and [SourceMod](https://www.sourcemod.net/), and running `sm_dump_netprops`
