### ISSUE TITLE
[QUESTION] Aimbot Detector

### ISSUE THREAD

**Issue by BlackYuzia** [BeepIsla/CSGO-Overwatch-Bot#154]
Hey @BeepIsla I saw what in aimbot detector you check event `player_death`.

You have any reasons why you didn't use `player_hurt` event?

I try just replace `player_death` to `player_hurt` (name of event) and I get 10 detects of aimbot:
![image](https://user-images.githubusercontent.com/25010528/95018900-07f9a280-066b-11eb-8e5c-7b4319fa84bd.png)

Legit cheaters have < 10 detects per game with `player_hurt` events too.
IDK why but legit or semi-rage players have lower detects like normal (without cheats) player.

```
		this.parent.demo.gameEvents.on("player_death", this.OnPlayerDeath.bind(this)); 
		this.parent.demo.gameEvents.on("player_hurt", this.OnPlayerDeath.bind(this)); // add new event
```

With that I get 12 detects. Just lol.
But rage cheater get more like 100 detects
![image](https://user-images.githubusercontent.com/25010528/95019065-07add700-066c-11eb-8984-97797a9fc2c3.png)

So, we should rename this detector to `rage_aimbot.js`? :eyes: 
Because legit or semi-rage players (I can share demo with semi-rage cheaters) can't be detected by this method.

**Comment by BeepIsla** [comment]
No reason other than didn't think of it at the time

**Comment by BlackYuzia** [comment]
> No reason other than didn't think of it at the time. I would keep it at "Aimbot" and also remove "player_death" if we use "player_hurt" instead.

if I use `player_hurt` and `player_death` I have more detects (~+1-5% of detects by `player_death`)

**Comment by BlackYuzia** [comment]
About demo: Cheaters use `triggerbot` (or autofire, autoshoot etc).
So when crosshair aim at enemy, cheat just auto shoot and kill enemy.

Aimbot detector can't detect this moment so he say - this player is clear.
How we can check what how long crosshair look at enemy model?
Or we can't do that with demo @BeepIsla ?

**Comment by BeepIsla** [comment]
> > No reason other than didn't think of it at the time. I would keep it at "Aimbot" and also remove "player_death" if we use "player_hurt" instead.
> 
> if I use `player_hurt` and `player_death` I have a bit more detects.

Because `player_death` and `player_hurt` trigger at the same time, if you kill someone you also hurt them. So you add an infraction when there is technically only one

**Comment by BeepIsla** [comment]
> **Note about semi-rage or legit cheaters:**
> Cheaters use `triggerbot` (or autofire, autoshoot etc).
> So when crosshair aim (look) at enemy, cheat just auto shoot and kill enemy.
> 
> Aimbot detector can't detect this moment so he say - this player is clear.
> How we can check what how long crosshair look at enemy model?
> Or we can't do that with demo @BeepIsla ?

I don't know, I don't think you can reliably check for this. Especially considering triggers bots can have configurable delay.

**Comment by BlackYuzia** [comment]
> Because player_death and player_hurt trigger at the same time, if you kill someone you also hurt them. So you add an infraction when there is technically only one

I think about that. But if I enable `player_hurt` and `player_death` I get 156 detects.
Only with `player_hurt` I get 85 detects.
Only with `player_death` I get 56 detects.
```
85 + 56 = 141;
141 !== 156;
```
Idk how it works actualy :D

**Comment by BlackYuzia** [comment]
I test this in myself.
```
both - 12 detects.
hurt - 10 detects.
death-  2 detects.
12 == 12 // there is normal ya. Okey. We need just use hurt at all.
```

**Comment by BlackYuzia** [comment]
**@BeepIsla I say what bot detect me (by using aimbot) when I replace `player_death` by `player_hurt`?**

**Comment by BlackYuzia** [comment]
![image](https://user-images.githubusercontent.com/25010528/95021669-0afc8f00-067b-11eb-87e0-9c057eefd26c.png)

**Comment by BeepIsla** [comment]
What

**Comment by BlackYuzia** [comment]
Count of detects has been increase after change event so, now, bot (this) think what I use aimbot in my demo.
So, I ask should we inc count of detects by aimbot?

**Comment by BlackYuzia** [comment]
```
		"minAimbot": 30,
```
I setup 30 by default in my config.
But idk how about other guys :thinking: 

I saw what detects of aimbot in rage cheaters `>= 50`, after `player_hurt` event - `>= 100`
