### ISSUE TITLE
Steamworks error

### ISSUE THREAD

**Issue by hammerx1337** [BeepIsla/CSGO-Overwatch-Bot#157]
Hello, I still get this error when trying to use steamworks, I did everything according to the instructions.
![Снимок](https://user-images.githubusercontent.com/72270982/95022655-4732ee00-0681-11eb-8d36-85c96a65e842.PNG)

**Comment by hammerx1337** [comment]
What do I need to do?

**Comment by BeepIsla** [comment]
What happens when you run `npm i ./extension/steam --save-optional`?

**Comment by hammerx1337** [comment]
![powershell_4a4mUYOaAw](https://user-images.githubusercontent.com/72270982/95023024-4dc26500-0683-11eb-9530-3cf8c9f4af24.png)

**Comment by BeepIsla** [comment]
Your path includes non-ascii characters. Move the `CSGO-Overwatch-Bot-master` folder somewhere else and make sure the path **only** includes `A-Z`, `a-z`, `0-9`, or spaces.

**Comment by hammerx1337** [comment]
I moved and still get this error
![powershell_AQ3RYfBZf2](https://user-images.githubusercontent.com/72270982/95023378-67fd4280-0685-11eb-934d-e16b82b92a72.png)

**Comment by BeepIsla** [comment]
Try `npm i ./extension/steam --save-optional` now

**Comment by hammerx1337** [comment]
![image](https://user-images.githubusercontent.com/72270982/95023468-d5a96e80-0685-11eb-8e8f-2366d0f9360d.png)

**Comment by BeepIsla** [comment]
`LNK1127` means the NodeJS library is corrupt in some way, weird. Try uninstalling and re-installing [NodeJS](https://nodejs.org/), don't forget to tick this box

![](https://camo.githubusercontent.com/73f8d5a707d3d072cc7e8ad4551c7a75ac7ca7e9/68747470733a2f2f692e696d6775722e636f6d2f5677714c4754342e706e67)

**Comment by hammerx1337** [comment]
Removed node-gyp from appdata / local and now it seems there are no errors, but after that nothing happens
![Снимок](https://user-images.githubusercontent.com/72270982/95024418-7fd7c500-068b-11eb-8dab-2cf47f12599f.PNG)

**Comment by BeepIsla** [comment]
Is there a new file created in the same folder? Something that looks like a debug log?

**Comment by hammerx1337** [comment]
in appdata or "CSGO-Overwatch-Bot-master"?

**Comment by BeepIsla** [comment]
In `CSGO-Overwatch-Bot-master`

**Comment by hammerx1337** [comment]
![Снимок](https://user-images.githubusercontent.com/72270982/95024956-df839f80-068e-11eb-93a3-9eb444e86935.PNG)

**Comment by BeepIsla** [comment]
Don't search for "debug", just send a screenshot of your folder where `config.json` and `index.js` are.

**Comment by hammerx1337** [comment]
![Снимок](https://user-images.githubusercontent.com/72270982/95025075-de06a700-068f-11eb-8435-5f6df1338459.PNG)

**Comment by BeepIsla** [comment]
Okay, my mistake. I have fixed it, download and try again.

If you don't want to download the whole file only download and update the file in `helpers/Steamworks.js`

**Comment by hammerx1337** [comment]
Thanks for the help, i reinstalled and still nothing happens
![11](https://user-images.githubusercontent.com/72270982/95025413-3f2f7a00-0692-11eb-981d-7646c431f965.PNG)

**Comment by BeepIsla** [comment]
Apologies one more time, I misspelled a word.

**Comment by hammerx1337** [comment]
Sorry, but now another error appears
![image](https://user-images.githubusercontent.com/72270982/95025603-9da92800-0693-11eb-9349-81ffa4063e8b.png)

**Comment by BeepIsla** [comment]
Slowly fixing everything... Sorry, one more time. This time please delete everything and download again.

**Comment by hammerx1337** [comment]
![image](https://user-images.githubusercontent.com/72270982/95025854-a4d13580-0695-11eb-9c81-8fc8ee5d817a.png)

**Comment by BeepIsla** [comment]
> Okay, my mistake. I have fixed it, download and try again.
> 
> If you don't want to download the whole file only download and update the file in `helpers/Steamworks.js`

This one more time...

**Comment by hammerx1337** [comment]
Now it works, thank you very much

**Comment by BeepIsla** [comment]
No problem, sorry it took so long and had so many errors!

**Comment by hammerx1337** [comment]
No problem
