### ISSUE TITLE
some errors after node index.js

### ISSUE THREAD

**Issue by muratcansimsek** [BeepIsla/CSGO-Overwatch-Bot#16]
node js version node js 12.16.1 LTS
OS : w7 sp1 x64

errors; 

C:\Users\ALMORA\Desktop\CSGO-Overwatch-Bot-master\CSGO-Overwatch-Bot-master>node
 index.js
internal/modules/cjs/loader.js:1195
    throw err;
    ^

SyntaxError: C:\Users\ALMORA\Desktop\CSGO-Overwatch-Bot-master\CSGO-Overwatch-Bo
t-master\config.json: Unexpected string in JSON at position 516
    at parse (<anonymous>)
←[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1192
:22)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:77:18)←[39m
    at Object.<anonymous> (C:\Users\ALMORA\Desktop\CSGO-Overwatch-Bot-master\CSG
O-Overwatch-Bot-master\index.js:15:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:1
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:74:12)←[39m
←[90m    at internal/main/run_main_module.js:18:47←[39m

C:\Users\ALMORA\Desktop\CSGO-Overwatch-Bot-master\CSGO-Overwatch-Bot-master>

**Comment by muratcansimsek** [comment]
gave error after adding the following codes
fixed after deleting codes, now working.

"steam_display": "#bcast_teamvsteammap",
    "team1": "Minecraft",
    "team2": "Roblox",
    "map": "coop_cementplant"

**Comment by BeepIsla** [comment]
According to the error your config and it wasn't valid. I recommend copy pasting your entire config into [JSONLint](https://jsonlint.com/). It will show you where the error is so you can correct it more easily.

Alternatively if you still want to include a custom rich presence on Steam copy paste your `config.json` here as a reply. Don't forget to censor out important things like API Key, Username, Password, etc.

**Comment by muratcansimsek** [comment]
![sorun yok](https://user-images.githubusercontent.com/25007736/75012287-bc570780-5492-11ea-8c58-b4168fbb287a.PNG)
no problem trying solved a few Overwatch cases, but this has been the case for the last 5 minutes. It says downloading, but like 5 minutes still waiting

**Comment by muratcansimsek** [comment]
i restart script now working 
![restart](https://user-images.githubusercontent.com/25007736/75012750-b9104b80-5493-11ea-8a5c-1ecaa6a6a002.PNG)
