### ISSUE TITLE
How to solved?

### ISSUE THREAD

**Issue by Chartone** [BeepIsla/CSGO-Overwatch-Bot#164]
PS D:\Docs\CSGO\CSGO Overwatch> npm ci
npm WARN prepare removing existing node_modules/ before installation

> protobufjs@6.10.1 postinstall D:\Docs\CSGO\CSGO Overwatch\node_modules\protobufjs
> node scripts/postinstall

> steam@1.0.0 install D:\Docs\CSGO\CSGO Overwatch\node_modules\steam
> node-gyp configure rebuild

D:\Docs\CSGO\CSGO Overwatch\node_modules\steam>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  Main.cpp
  win_delay_load_hook.cc
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(29,82): error C2039: 'ToLocalChecked': is not a member of '
v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(38,115): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(45,123): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(52,124): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(91,115): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(98,123): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(122,64): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(131,64): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(132,65): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(133,64): error C2039: 'ToLocalChecked': is not a member of
'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(122,6): warning C4996: 'v8::Object::Set': was declared depr
ecated [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(131,6): warning C4996: 'v8::Object::Set': was declared depr
ecated [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(132,6): warning C4996: 'v8::Object::Set': was declared depr
ecated [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(133,6): warning C4996: 'v8::Object::Set': was declared depr
ecated [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(144,115): error C2039: 'ToLocalChecked': is not a member of
 'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(151,123): error C2039: 'ToLocalChecked': is not a member of
 'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\src\Main.cpp(158,124): error C2039: 'ToLocalChecked': is not a member of
 'v8::Local<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
C:\Users\Chartone\AppData\Local\node-gyp\Cache\12.19.0\include\node\v8.h(1399): message : see declaration of 'v8::Local
<v8::String>' [D:\Docs\CSGO\CSGO Overwatch\node_modules\steam\build\steam.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "rebuild"
gyp ERR! cwd D:\Docs\CSGO\CSGO Overwatch\node_modules\steam
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
added 265 packages in 7.085s
PS D:\Docs\CSGO\CSGO Overwatch>

**Comment by BeepIsla** [comment]
You are trying to install with Steamworks addon, which needs to be compiled with a C++ compiler. It is marked as **optional** in the dependencies so it *should not* automatically install when you run `npm ci`. Download again and try again.
