### ISSUE TITLE
[SUGGESTION] Wallhack Detector Hurt Event

### ISSUE THREAD

**Issue by BlackYuzia** [BeepIsla/CSGO-Overwatch-Bot#165]
My suggestion - change `player_death` event in **wallhack detector** to `player_hurt`.
But we have the same situation like with **aimbot detector.**

`player_hurt` event can call a lot much more hits (triggers).
When I will try do this I will get a lot more false positive :eyes: 

Why we won't use `player_death` event?
**Cheater can only hurt but not kill enemy.**

**Comment by BeepIsla** [comment]
Look at the [player_hurt](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#player_hurt) and [player_death](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#player_death) events first.

Hurt does not provide the same information as death so this is not possible unless you manually parse the maps from the compiled BSP and then do a trace from attacker to victim to detect objects between them. I wanted to do this but there were no good map parsers out there for JS and I don't really want to make one myself, so I just opted for the death event instead.
