### ISSUE TITLE
Stuck in Downloading Case

### ISSUE THREAD

**Issue by goxostar** [BeepIsla/CSGO-Overwatch-Bot#166]
Hi there,

I installed script with additional components (VS Build,Python etc.) and running with STEAMWORKS. There is no errors and it starts successfully, but generally after 5 or 8 cases script stuck in stage "Downloading Case." I tried to download case from CS:GO, also i couldn't download it.

Could someone help me please? My network connection is fine, but should i needed to use VPN?

**Comment by BeepIsla** [comment]
What does the console say? Is the download link a china demo url?

**Comment by goxostar** [comment]
I don't now right now. I'll take a screenshot if it stuck again.

**Comment by goxostar** [comment]
https://prnt.sc/uyjdok

This time, it completed 14 cases and stuck again. Take a look on screenshot it is waiting like this. Also yes, demo url is from china. ( .cn )

**Comment by BeepIsla** [comment]
This is a problem that has been known for a very long time, I don't know why or how this happens. For one Overwatch demos from China are extremely ratelimited, you can only download with about 200 kb/s. Unpacking or parsing the demo sometimes entirely fails for unknown reasons. These things are already talked about in issue #30, so this might just be a duplicate. At the time there is no solution for this as far as I know, sadly.
