### ISSUE TITLE
Check a specific demo and a specific player

### ISSUE THREAD

**Issue by kmko1337** [BeepIsla/CSGO-Overwatch-Bot#175]
My english is not the best one but u will understand, so my idea was to do "index.js <demolink> <steamid64>" and it check this person for aimbot, wallhack, antiaim, etc.

**Comment by BeepIsla** [comment]
README:

> You can forcefully parse a demo by running `node force.js`, it will ask you for a demo file path and a suspect SteamID. Alternatively just use `node force.js <Demo> <SteamID>`

Install NodeJS, run `node force.js`, follow instructions.

**Comment by kmko1337** [comment]
? Enter the name of the demo: what i put there cuz link of the demo doesn't work it doesn't download it 
? Suspect SteamID: Is this normal steamid or 64?

**Comment by BeepIsla** [comment]
> ? Enter the name of the demo: what i put there cuz link of the demo doesn't work it doesn't download it

Download the demo, put the file in the folder, write the file name

> ? Suspect SteamID: Is this normal steamid or 64

SteamID, SteamID3, or SteamID64 - https://steamid.io/

**Comment by kmko1337** [comment]
Thanks, a nice idea was to put the share link (from demo) and it download it etc.

**Comment by BeepIsla** [comment]
No. A share link requires a Steam connection with an account. `force.js` is specifically designed to not make a Steam connection.
