### ISSUE TITLE
stuck at downloading demo

### ISSUE THREAD

**Issue by saintchivo** [BeepIsla/CSGO-Overwatch-Bot#176]
Hi! I always get stuck at downloading demo. I tried to wait for it like for 30 mins but it never continue. What shall I do?

**Comment by xSuspect** [comment]
does not work on the old version or the new one (even if you download and do it manually)
![image](https://user-images.githubusercontent.com/45514952/97809285-a54cf400-1c74-11eb-8943-2da0c5ce2ba6.png)
http://replay234.wmsj.cn/730/003445024129609105642_0673334195.dem.bz2 old 
 http://replay228.wmsj.cn/730/003445036542064591052_0602267388.dem.bz2 new 
I don't think it works on other demos
off china :)

**Comment by KillaBoi** [comment]
I'm not having any issues with chinese cases, they're totally fine for me rightnow

**Comment by saintchivo** [comment]
![image](https://user-images.githubusercontent.com/73790513/97873512-b66c3280-1d52-11eb-95ef-06ed063c0d21.png)

Here's where I'm getting stuck at. I tried restarting it three times but it is still stuck. But when I try again some other time, it continues. I don't know what's the problem.

**Comment by BeepIsla** [comment]
Try downloading the demo yourself

**Comment by xSuspect** [comment]
> Try downloading the demo yourself

Works, but not at all, especially those in China.

**Comment by muriloporto** [comment]
For fix, need Re Install CSGO.

Unistall and download again

**Comment by BeepIsla** [comment]
Your CSGO installation has nothing to do with this.

**Comment by BeepIsla** [comment]
Duplicate #30
