### ISSUE TITLE
Overwatch-Bot - demo of our matches

### ISSUE THREAD

**Issue by magalhaescmc** [BeepIsla/CSGO-Overwatch-Bot#177]
I'm sorry if I'm in the wrong place, I didn't know where to contact. I would like to know if from your Overwatch-Bot, it would be possible to develop a script to play a demo of our matches, and take the doubt of a player that we think is suspicious. would that be possible? thanks for listening

**Comment by BeepIsla** [comment]
Read the README?

> You can forcefully parse a demo by running `node force.js`, it will ask you for a demo file path and a suspect SteamID

Download the demo, copy the demo into the scripts directory.
