### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Falghere** [BeepIsla/CSGO-Overwatch-Bot#18]
It would be nice to have two things

one of them very useful:
1 database that stores all SteamID of all suspects and then when you execute a command show / check who has been banned and who has not been

a second thing would be nice to get information from the demo during the analysis
example: 
map: d_dust2 - result: 10x3

a third question totally extremist and a little absurd but that would be cool, would it be possible to do something like that analyze in real time? like a spectator to know if the enemy team is cheating or not

**Comment by BeepIsla** [comment]
1. A ban checker is of scope for this project. But I am planning a rewrite and if I feel good I might add it but don't get your hopes up

2. This is all already available if you enable logging in the config

3. Without reverse engineering GOTV this is not possible and I will not do that.

**Comment by Falghere** [comment]
oh yes I understand, about the "2" it would be nice if it shows up in the CMD while analyzing it instead of keeping this data in a log, if possible I would be very grateful if you put something to check the bans or for something to alert someone was banned

**Comment by Falghere** [comment]
the aimbot algorithm is very bad (I did a test analyzing a player spinning and only managed to detect 1 aimbot), if you re-write it it would be nice to improve it
