### ISSUE TITLE
Finde a solution for this

### ISSUE THREAD

**Issue by Spooonky** [BeepIsla/CSGO-Overwatch-Bot#184]
I analyzed my own demo. I've been cheating the whole game. 
Perhaps you can improve your Overwatch bot even further with this demo. Possibly on the basis of headshots in the game and the weapon with which the headshots were taken. Furthermore, and if possible, the reaction time after surfacing behind a wall should be taken into account. If you need more demos, let me know. I apologize for the bad english i used the google translator

steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-H5ZqW-XYyKV-4nx5u-2aGap-j4FdH

**Comment by Spooonky** [comment]
https://prnt.sc/vp5a64

**Comment by BeepIsla** [comment]
Just the Aimbot detector should likely pick this up as 50+ detections, but none of the ways the bot detects cheating are good in any way and I don't care enough to improve them.
