### ISSUE TITLE
Overwatch bot

### ISSUE THREAD

**Issue by ESLCarlos1610** [BeepIsla/CSGO-Overwatch-Bot#186]
Hey, danke für die Problemlösung, hat geklappt. Ich wollte mal fragen, ob ich mit dem Bot, auch über einen Server mehrere Accs laufen lassen kann damit 5-20 accounts overwatches gleichzeitig machen. Mit autorestart usw

**Comment by BeepIsla** [comment]
Download multiple times & Use PM2

**Comment by ESLCarlos1610** [comment]
what is pm2`?

**Comment by BeepIsla** [comment]
https://pm2.keymetrics.io/

Starts, monitors, auto-restarts, etc the bot, instead of `node index.js` you do `pm2 start index.js --name "Overwatch Bot 1"`

**Comment by ESLCarlos1610** [comment]
thanks

**Comment by ESLCarlos1610** [comment]
Kann man whitlisten? Also accs die nicht vom OW gebannt werden sollen

**Comment by BeepIsla** [comment]
No

**Comment by ESLCarlos1610** [comment]
Login with saved loginKey failed. Logging in without loginKey...

what should i do?

**Comment by ESLCarlos1610** [comment]
https://i.imgur.com/VwPADqL.png

**Comment by BeepIsla** [comment]
Maybe a bug, wrong usage, idk - related: https://github.com/BeepIsla/CSGO-Overwatch-Bot/issues/142#issuecomment-697885262

When it tries to login with a loginKey and that fails it shouldn't retry that again, it should ask for login details. It also happens when the password is wrong, make sure your config is correct and everything is how its described in the README.

**Comment by ESLCarlos1610** [comment]
https://i.imgur.com/pGCccqL.png

**Comment by BeepIsla** [comment]
- [Google](https://www.google.com/search?q=about_execution_policies)
- or [use a command prompt instead](https://www.google.com/search?q=how%20to%20open%20command%20prompt%20in%20folder)

**Comment by ESLCarlos1610** [comment]
https://i.imgur.com/sgRDz95.png
i got this now, how do i start the bot to watch?

**Comment by BeepIsla** [comment]
It says its online so its running and will automatically restart when it crashes or something.

**Comment by ESLCarlos1610** [comment]
but if i go to my profile, this isnt ingame

**Comment by ESLCarlos1610** [comment]
https://i.imgur.com/UjzOIBJ.png

**Comment by ESLCarlos1610** [comment]
watching is disabled

**Comment by BeepIsla** [comment]
Then check the logs and see what is doing `pm2 logs "Overwatch Bot 1"` if its doing nothing then its probably waiting for a Steam Guard key, so stop it with `pm2 stop <name>` then start it manually `node index.js`, input Steam Guard (it should save automatically), close it with `CTRL + C` then start the bot again `pm2 start <name>` and again check the logs to see what its doing

**Comment by ESLCarlos1610** [comment]
you got discord? i might need your suppert xD
i dont get the problem

**Comment by BeepIsla** [comment]
I don't give out my Discord, either give up or follow instructions in the README. If the stuff I mentioned above doesn't work I can't help anymore.

**Comment by ESLCarlos1610** [comment]
i do everything like you said, but the problem is, the Steam Guard Code didnt safe, so u know any other way?

**Comment by BeepIsla** [comment]
Disable Steam Guard  ¯\_(ツ)_/¯

**Comment by ESLCarlos1610** [comment]
Its my main account xD

**Comment by ESLCarlos1610** [comment]
please i need you support :)

**Comment by BeepIsla** [comment]
I told you everything. Valve silently prevents Overwatch botting anyways
