### ISSUE TITLE
Found 1 moderate severity vulnerability

### ISSUE THREAD

**Issue by zipwq** [BeepIsla/CSGO-Overwatch-Bot#19]
When i write "npm i" an error appears: added 165 packages from 157 contributors and audited 268 pacages in 21.419s
found 1 moderate severity vulnerability
run "npm audit fix" to fix them, or "npm audit" for details.

When i write "npm audit fix" it appears: fixed 0 of 1 vulnerability in 268 packages. 1 vulnerability requiered manual review and could not be updated.

**Comment by BeepIsla** [comment]
I looked into that yesterday. The dependency with the vulnerable code is "minimist"

As far as I can tell the vulnerable code is not used anywhere, so this can be ignored.

Even if I would try fixing it a problem would be one dependency deep down the tree requiring an extremely old version of minimist which would make updating it very hard.

**Comment by zipwq** [comment]
Ok, but i can't install it.

**Comment by BeepIsla** [comment]
There is no error in any of what you sent. Just a warning which can be ignored.

What happens when you run it?

**Comment by zipwq** [comment]
Nothing, the warning persists:
![overwatchbot-issue](https://user-images.githubusercontent.com/62344633/76978416-52ba0400-693f-11ea-8dc6-d3ce05b68e00.png)

**Comment by BeepIsla** [comment]
Don't run any install again, or audit fix, just run the bot like normal. (`node index.js`)

**Comment by zipwq** [comment]
Working! Thanks a lot!
