### ISSUE TITLE
eror ? 

### ISSUE THREAD

**Issue by kanary08** [BeepIsla/CSGO-Overwatch-Bot#192]
![Adsız](https://user-images.githubusercontent.com/77010601/103658569-70af2e80-4f7c-11eb-8fa6-299028122e9d.jpg)

**Comment by BeepIsla** [comment]
Fix your JSON, it is invalid.

**Comment by kanary08** [comment]
![123](https://user-images.githubusercontent.com/77010601/103772075-f47b2080-5039-11eb-8c79-879ebb763030.jpg)

**Comment by kanary08** [comment]
is it OKy

**Comment by kanary08** [comment]
![12](https://user-images.githubusercontent.com/77010601/103772494-b5010400-503a-11eb-918c-27a57426bbc8.jpg)
