### ISSUE TITLE
error with CSGO:Overwatch Bot

### ISSUE THREAD

**Issue by AndreYus296** [BeepIsla/CSGO-Overwatch-Bot#196]
Please help me with this 
![Screenshot_23](https://user-images.githubusercontent.com/78605434/107048786-ffa8a400-67d1-11eb-93f3-164d2fa997a4.png)
error

**Comment by BeepIsla** [comment]
Fix your config, it is invalid.

**Comment by AndreYus296** [comment]
what do u mean with fix config?Can u send me again a fresh one ?Btw in my config does not appear apk key steam

**Comment by BeepIsla** [comment]
Just use the example config provided: https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/master/config.json.example
