### ISSUE TITLE
Player not found!

### ISSUE THREAD

**Issue by pelasta** [BeepIsla/CSGO-Overwatch-Bot#198]
hey,

I'm getting this error from time to time, usually, I wait for the case to expire once this happens,

**Error: Player not found**

_| Checking for Overwatch access...
| --------------------------------------------------
|                  Case ID: 3465559824245194909
|             Download URL: http://replay234.wmsj.cn/730/003465537247749603449_1117282947.dem.bz2
|             Total Rounds: 17
|          Rounds to watch: 8
| Overwatch starting round: 6
|                  Suspect: https://steamcommunity.com/profiles/76561199141301564
| ----- The whole demo will be analyzed ----
| Downloading demo..._

Not sure if this is a VALVE side issue or not, thought I should share, thanks!

**Comment by BeepIsla** [comment]
What do you mean player not found? No such error exists in my code
