### ISSUE TITLE
[QUESTION] Delay

### ISSUE THREAD

**Issue by BlackYuzia** [BeepIsla/CSGO-Overwatch-Bot#200]
Hi @BeepIsla 

Why we have delay before we send results of check demo?
Delay is set to 4.58 min. If I didn't mistake. 

I mean, in demo we can fast skip demo (by set speed x10) and send verdict.

**Comment by BeepIsla** [comment]
If you send results too fast it gets ignored, tHts why I added the delay option, you can just set it to 0 to disable it though.
