### ISSUE TITLE
STEAMWORKS Error

### ISSUE THREAD

**Issue by Dyzery02** [BeepIsla/CSGO-Overwatch-Bot#204]
I have an issue starting node index.js STEAMOWRKS, cannot add anything up, only tried reinstalling, looking forward to fix it.
![Screenshot 2021-05-25 234926](https://user-images.githubusercontent.com/37552652/119566760-2f48df80-bdb4-11eb-8bb8-01bb07511815.png)

**Comment by BeepIsla** [comment]
Oops.

This seems to come from the module not installing correctly, it is suppose to create a "data" folder in your directory with sub folders and binaries.

**Comment by BeepIsla** [comment]
Actually taking a quick look just now, I think I found the source of the issue.

**Comment by BeepIsla** [comment]
If the issue persists please re-open

**Comment by Dyzery02** [comment]
I did an `<npm update>` after that, `<npm i ./extension/steam>` and I got a bunch of errors, attaching log, tried again to run STEAMWORKS, same problem, *error code ELIFECYCLE*.
[2021-05-26T13_39_52_741Z-debug.log](https://github.com/BeepIsla/CSGO-Overwatch-Bot/files/6547140/2021-05-26T13_39_52_741Z-debug.log)

**Comment by BeepIsla** [comment]
I meant update as in: Download the bot again

**Comment by Dyzery02** [comment]
Seems to work now just fine, sorry for the delay.

**Comment by Dyzery02** [comment]
After first install and launch without steamworks, then steamworks it worked fine, after closure, when I launched csgo and closed it, command-bot did not work that time, even after reinstall it did not work, attaching log.
[2021-05-26T15_23_17_136Z-debug.log](https://github.com/BeepIsla/CSGO-Overwatch-Bot/files/6547872/2021-05-26T15_23_17_136Z-debug.log)

**Comment by xSuspect** [comment]
![image](https://user-images.githubusercontent.com/45514952/119709613-b3a36d00-be5d-11eb-8683-0ea49d64f3d3.png)

**Comment by BeepIsla** [comment]
There should be no difference between installs, the logs just say

> 1674 info lifecycle steam@1.0.0~install: **Failed to exec install script**

With no further detail as to why this would happen.

**Comment by Dyzery02** [comment]
![Capture](https://user-images.githubusercontent.com/37552652/119983920-7a880b80-bfc9-11eb-9f64-cd59bfcb2522.PNG)
![Capewfqfweture](https://user-images.githubusercontent.com/37552652/119983926-7c51cf00-bfc9-11eb-8916-53ade90293fe.PNG)

**Comment by BeepIsla** [comment]
Try running in command prompt instead, if that doesn't help you have to install all required build tools, NodeJS will do that automatically as mentioned [here](https://github.com/BeepIsla/CSGO-Overwatch-Bot#steamworks).

**Comment by Dyzery02** [comment]
![image](https://user-images.githubusercontent.com/37552652/120083971-25392080-c0d5-11eb-86a0-b46eca4d5be6.png)
NodeJS was installed at first and now reinstalled with checkbox on plugins, about Python, it brags about it when installing and running index.js. I have the latest version installed, but it still does not run.

**Comment by BeepIsla** [comment]
It tells you what to do:

> Node-gyp should be able to find and use Python (automatically). If not you can try one of the following options:
> 
> - npm config set python "<path_to_python>"

I think you have to use Python2, not Python3, but I am not sure.

**Comment by Dyzery02** [comment]
Just fixed it, linked a path to python (newest version) and had to install visual studio C++ desktop works with minor errors, but still I do not receive overwatch xp bonus, is it possible to run file path in cmd and as an administrator? if so how? when the bot is running should cs:go be open or closed?

**Comment by BeepIsla** [comment]
The Steamworks method simulates CSGO, you should not have the actual CSGO client running while using it.
