### ISSUE TITLE
[SUGGESTION] More detailed verdict reports. e.g elaborate on griefing. How many team kills, how much total team damage etc

### ISSUE THREAD

**Issue by creeperdude997** [BeepIsla/CSGO-Overwatch-Bot#206]
Greifing 
-Total team kills
-Total team damage
-Total team damage/kill after all enemies are dead

**Comment by BeepIsla** [comment]
There is a `writeLog` option in your `config.json`, if set to `true` it will write a JSON file to disk with more information.

Example for what it would show for griefing:

```json
[
    {
        "tick": 32892,
        "type": "damage",
        "damage": 23
    },
    {
        "tick": 32921,
        "type": "damage",
        "damage": 12
    },
    {
        "tick": 33201,
        "type": "death"
    }
]
```
