### ISSUE TITLE
[SUGGESTION] Add some form of Bhop detection. 

### ISSUE THREAD

**Issue by creeperdude997** [BeepIsla/CSGO-Overwatch-Bot#207]
It would need to be fine tuned as sometime people, even myself, can hit long bhop lines but some form of bhop detection would be nice. Maybe based on player speed and time. So if player pseed is higher than maximum knife run speed for an extended time then it flags or something.

**Comment by BlackYuzia** [comment]
Hmm. I **suppose** what we get false-positive sometimes.

I mean, we can just bind on **mouseScroolUp** and **mouseScrollDown** buttons `+jump` and just scroll mouse.
That means what our detects by `player_jump` event would **detect cheaters** and also **mouse scrollers**.

**Comment by creeperdude997** [comment]
even mousse scrollers cant bhop for that long. Maybe the detection is set for a set time and that adds 1 point b ut if they do it x times it marks a bhop.

**Comment by BlackYuzia** [comment]
Hmm, actualy yes, if real user can bhop 5 times (i.e. that max value), we can check did that user bhop more like 5 times in one line with speed >= 180-200 for example. After that inc. count of detects. If detects >= x - cheater!

**Comment by creeperdude997** [comment]
then as an extra layer, check if they do a 5 hop line multiple times in the game

**Comment by BeepIsla** [comment]
It is not hard to detect tick-perfect bhopping and its very unlikely you can do it perfectly consistently for more then 5 in a row

**Comment by creeperdude997** [comment]
I use this program as an overwatch assistant. It would be cool to see it merged with something like https://github.com/ZaharX97/OWReveal to allow it to collect and download its own cases using packet sniffing so that its not interacting with the account. At the current moment i download the demo using that tool and then usse force.js to enure im not actually uing it to automatically ubmit verdicts etc

**Comment by BlackYuzia** [comment]
> It is not hard to detect tick-perfect bhopping and its very unlikely you can do it perfectly consistently for more then 5 in a row

You mean what cheaters not every time use perfect bhop and count of jumps, sometimes, can be less like 5?

@BeepIsla

**Comment by BeepIsla** [comment]
Update and try it out, record some demos yourself and see if you can false-positive trigger it
