### ISSUE TITLE
[SUGGESTION] Tick recording for innfraction detection

### ISSUE THREAD

**Issue by creeperdude997** [BeepIsla/CSGO-Overwatch-Bot#209]
for example on a wall kill, have the replay tick off the wall kill recorded about 10 sseconds before or so we can watch it. Same with bhop etc

**Comment by BeepIsla** [comment]
- The log files tell you the exact moment something happened.

- Overwatch demos are recorded at 32 tick per second

So just calculate `<tick_in_logs> - (32 * 10)` to go back 10 seconds before the infraction happened, finally in-game just enter `demo_gototick <value>` into the console.
