### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wytrom** [BeepIsla/CSGO-Overwatch-Bot#212]
![image](https://user-images.githubusercontent.com/53312166/124341730-da5b6e80-db94-11eb-843a-88406135b908.png)

The bot was working perfectly, after 20 cases it disconnected, I tried to reopen it but I get this error, I reinstalled the bot completely and I was unsuccessful. 

I need any help thanks for the work

**Comment by xSuspect** [comment]
Is Steam not YOU

**Comment by wytrom** [comment]
thanks! apparently normalized
