### ISSUE TITLE
Steamworks did not work

### ISSUE THREAD

**Issue by kamyczeek** [BeepIsla/CSGO-Overwatch-Bot#213]
System: Windows 10 Home 20H2

![image](https://user-images.githubusercontent.com/80060115/126877008-a2a06621-97f4-4e36-a1b3-73bf5ff8810a.png)

**Comment by BeepIsla** [comment]
It tells you what to do right there in the error. Try it and tell me how it goes.

**Comment by kamien2137** [comment]
I have tried, it does not help
![image](https://user-images.githubusercontent.com/80060115/126877177-30e50c6b-9b9c-401d-a93b-0c6221b4fc7f.png)

**Comment by BeepIsla** [comment]
Go to `extension/steam` and try running `node-gyp configure rebuild && node postinstall.js`

**Comment by kamien2137** [comment]
still the same

**Comment by BeepIsla** [comment]
Doing this

> Go to `extension/steam` and try running `node-gyp configure rebuild && node postinstall.js`

Must either say its successful or will return a big error detailing what went wrong. What happened?

**Comment by kamien2137** [comment]
![image](https://user-images.githubusercontent.com/80060115/126881203-b51e97a6-836a-451b-98c1-7b3c0b8437a0.png)
`The projects in this solution are compiled individually. To enable parallel compilation, add the "-m" switch.
   Main.cpp
   win_delay_load_hook.cc
      Creation of the c: \ aakamov \ extension \ steam \ build \ Release \ steam.lib library and the object c: \ aakamov \ extension \ steam \
   build \ Release \ steam.exp
   Code generation is in progress
   Previous IPDB not found, fall back to full compilation.
   All 459 functions were compiled because no usable IPDB / IOBJ from previous compilation was found.
   Code generation is complete`

**Comment by BeepIsla** [comment]
Seems to compile successfully. If you try to run the bot now it still outputs the same error saying "Failed to automatically install required addon."?

**Comment by kamien2137** [comment]
yes,
![image](https://user-images.githubusercontent.com/80060115/126881326-fdd8c5bd-ecca-4025-ac9f-fff00b547af5.png)

**Comment by BeepIsla** [comment]
Try replacing the `helpers/Steamworks.js` file with this one, try to start the bot again and tell me what error it logs this time. [Steamworks.zip](https://github.com/BeepIsla/CSGO-Overwatch-Bot/files/6873074/Steamworks.zip)

**Comment by kamien2137** [comment]
![image](https://user-images.githubusercontent.com/80060115/126881405-4e0c031c-351d-414f-a01e-c6d4f88e03ff.png)

**Comment by BeepIsla** [comment]
So it says it successfully installed it but then when you run it it simply can't find it? I don't quite know why this happens for you. Maybe your Anti Virus is removing the compiled files thinking it is a virus?

**Comment by kamien2137** [comment]
i only have a defender, but it's also turned off

**Comment by kamyczeek** [comment]
i tested on a second pc and i have the same problem

**Comment by BeepIsla** [comment]
I have no idea why this is happening to be honest.

**Comment by kamyczeek** [comment]
I solved the problem, deleted the folder "node_modules", installed steam, recompiled the files in "extension \ steam", then I got an error about missing files in "./build". I put the files from "extension \ steam \ build" to "./build" and it works.
