### ISSUE TITLE
problem with another program 

### ISSUE THREAD

**Issue by SeuzNsk** [BeepIsla/CSGO-Overwatch-Bot#214]
used csgo commend bot for a very long time. Today I decided to use it again and there was such a problem. I didn’t know where it’s can  to contact you, so I wrote here  
![IMG_20210815_014736_631](https://user-images.githubusercontent.com/88948977/129460969-97513802-2549-4cca-9725-9cb423a1bd38.jpg)

**Comment by BeepIsla** [comment]
If a repository is archived, like the commend bot, that means it no longer is supported. If you have issues you are on your own.

Going to [the issues tab](https://github.com/BeepIsla/csgo-commend-bot/issues) would probably give you **all** the information you need to know that it has been patched and I didn't fix it.
