### ISSUE TITLE
npm ci error

### ISSUE THREAD

**Issue by loladolares** [BeepIsla/CSGO-Overwatch-Bot#215]
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm ci
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
![1](https://user-images.githubusercontent.com/88960995/129469687-7ff2147d-9bcf-4236-8c06-542d419987ab.PNG)

**Comment by loladolares** [comment]
https://www.c-sharpcorner.com/blogs/npm-is-not-recognized-from-visual-studio

**Comment by BeepIsla** [comment]
Just use command prompt (cmd) instead of powershell
