### ISSUE TITLE
is it patched ? 

### ISSUE THREAD

**Issue by YSSSXD** [BeepIsla/CSGO-Overwatch-Bot#218]
@BeepIsla 

how to fix it
![Screenshot_13](https://user-images.githubusercontent.com/76930629/133682652-72d34cfb-dccf-43bf-b712-d83a8ec466dc.jpg)

**Comment by BeepIsla** [comment]
Do **not** post about an unrelated project here. If a project is archived that means it is no longer maintained or cared for. If you have issues you are on your own. The most recent and pinned issue thread on that repository gives you all the information you need.
