### ISSUE TITLE
Unable to use STEAMWORKS

### ISSUE THREAD

**Issue by 45O** [BeepIsla/CSGO-Overwatch-Bot#219]
![image](https://user-images.githubusercontent.com/73535746/137060273-67b9356a-bce6-4f9e-baea-66b645cc54e1.png)
This is when I try to run "npm i ./extension/steam\", Because of this error when I try to run STEAMWORKS
![image](https://user-images.githubusercontent.com/73535746/137060413-756162d8-d7d8-4953-80f8-edb5a3c7015d.png)
I apologise if it's an easy fix

**Comment by BeepIsla** [comment]
You are typing 

> npm i ./extension/steam\"

Try typing

> npm i ./extension/steam

**Comment by 45O** [comment]
![image](https://user-images.githubusercontent.com/73535746/137060825-d3f57daf-e2a4-4cc8-b187-0e3d732879b5.png)
This is the out come, then I tried to run steamworks and 


![image](https://user-images.githubusercontent.com/73535746/137060917-2b128f78-a3a5-48fc-835d-88c3677a2081.png)

**Comment by BeepIsla** [comment]
Open up the `package.json` file in the `CSGO-Overwatch-Bot-master` directory with a text editor and send the contents of it here

**Comment by 45O** [comment]
{
  "name": "steam",
  "description": "Steamworks native addon for the CSGO Overwatch bot",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "install": "node-gyp configure rebuild",
    "postinstall": "node postinstall.js"
  },
  "keywords": [],
  "author": "BeepIsla",
  "license": "MIT",
  "gypfile": true,
  "dependencies": {},
  "repository": {}
}

**Comment by BeepIsla** [comment]
Not this one, there is another one in the parent folder

**Comment by 45O** [comment]
{
  "name": "csgo-overwatch-bot",
  "version": "2.6.5",
  "description": "Automatically solves Overwatch cases. Its not good but its trying.",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/BeepIsla/CSGO-Overwatch-Bot.git"
  },
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "BeepIsla",
  "license": "AGPL-3.0",
  "dependencies": {
    "almost-equal": "^1.1.0",
    "bytebuffer": "^5.0.1",
    "cheerio": "^1.0.0-rc.3",
    "cli-table3": "^0.6.0",
    "colors": "^1.4.0",
    "demofile": "^1.8.0",
    "inquirer": "^7.3.3",
    "node-fetch": "^2.6.1",
    "protobufjs": "^6.10.1",
    "serialize-error": "^7.0.1",
    "steam-totp": "^2.1.1",
    "steam-user": "^4.18.0",
    "steamid": "^1.1.3",
    "unbzip2-stream": "^1.4.3",
    "unzipper": "^0.10.11",
    "vdf-parser": "^1.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.13.0"
  },
  "optionalDependencies": {
    "steam": "file:extension/steam"
  },
  "bugs": {
    "url": "https://github.com/BeepIsla/CSGO-Overwatch-Bot/issues"
  },
  "homepage": "https://github.com/BeepIsla/CSGO-Overwatch-Bot#readme",
  "directories": {
    "test": "tests"
  }
}

**Comment by BeepIsla** [comment]
Weird. It looks like it installs successfully when executing `npm i ./extension/steam` but it doesn't add it to the modules list?

Download this file https://pastebin.com/raw/5VMM15hW and save it as `Steamworks.js` inside the `helpers` folder, you should already see a `Steamworks.js` file, just replace it with the new one. Once done try running again using `node index.js STEAMWORKS`, it should now log more details that might help

**Comment by 45O** [comment]
![image](https://user-images.githubusercontent.com/73535746/137062607-71c8d087-ed64-4873-a7b5-bfcb4d5503c5.png)
Here you go

**Comment by BeepIsla** [comment]
I don't know why this is happening.

**Comment by 45O** [comment]
Think it's worth a try at reinstalling it all?

**Comment by BeepIsla** [comment]
You can try

**Comment by 45O** [comment]
Re installed all of it, and was greeted by the same error, saved that txt as the steamworks.js again and exact same issue

**Comment by BeepIsla** [comment]
My last try would be maybe: Open a command prompt inside the `extension/steam` folder and run `npm run install`, if there are no errors it should now work?

**Comment by 45O** [comment]
![image](https://user-images.githubusercontent.com/73535746/137064665-51b62d4b-1d16-420c-91ff-589dc7821f47.png)
oof was worth a shot

**Comment by BeepIsla** [comment]
Well this now tells us why it fails. It can't build the module because the compiler is missing. [Make sure you installed the necessary build tools when installing NodeJS](https://github.com/BeepIsla/CSGO-Overwatch-Bot#steamworks)

**Comment by 45O** [comment]
I reinstalled and included the tools yesterday, I'll try again though

**Comment by 45O** [comment]
Tried reinstalling the Tools and now it is having issues with Python 
![image](https://user-images.githubusercontent.com/73535746/137065811-a0514660-688c-4739-a245-4e1ecacf06ed.png)

**Comment by BeepIsla** [comment]
Do you have python installed? If not download and install it

**Comment by 45O** [comment]
I do, I have 3.8.0 installed for months

**Comment by BeepIsla** [comment]
Try specifically installing Python2 and make sure to tick the checkbox to also add Python to PATH

**Comment by 45O** [comment]
Installed 2.7, ran NPM CI
![image](https://user-images.githubusercontent.com/73535746/137067775-b362d6a4-0265-4993-8922-48a704244317.png)

**Comment by 45O** [comment]
Installed python 2.7 at PATH, and it isn't finding python when I ran node-gyp configure rebuild

**Comment by BeepIsla** [comment]
It tries to build the module using a file that doesn't exist for some reason. I assume there might be left overs from a previous installation of the Visual Studio Build Tools causing issues. I don't know how you could fix this
