### ISSUE TITLE
error while installing npm

### ISSUE THREAD

**Issue by wollframium** [BeepIsla/CSGO-Overwatch-Bot#221]
I use another script of yours (that is closed) for other purposes, it is needed so as not to download the csgo but run it (other scripts like asf sam do not fit them, they do not have a real run of csgo), and just recently changed windows, and wanted to reinstall your software but gives such errors.
 ```
 npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 219 packages, and audited 221 packages in 54s

14 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (5 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
Can this be fixed or should I be looking for alternatives?

**Comment by BeepIsla** [comment]
1. If something is archived, I don't support it anymore
2. Don't open an issue on unrelated repositories
3. There is no error in what you've shown

**Comment by wollframium** [comment]
> 1. Если что-то заархивировано, я это больше не поддерживаю
> 2. Не открывайте вопрос о несвязанных репозиториях
> 3. В том, что вы показали, нет предупреждения



I use all overtach for my own purposes, but when installing overtach, the same errors were

**Comment by wollframium** [comment]
> 1. If something is archived, I don't support it anymore
> 2. Don't open an issue on unrelated repositories
> 3. There is no warning in what you've shown
the overtach script worked despite errors
PS D:\csgo-commend-bot-master\CSGO-Overwatch-Bot-master> npm ci
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

added 283 packages, and audited 286 packages in 48s

64 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

**Comment by wollframium** [comment]
the overtach script worked despite errors

**Comment by wollframium** [comment]
but still you are crazy if you have such a reaction.
