### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by hammerx1337** [BeepIsla/CSGO-Overwatch-Bot#231]
hello, when I write npm ci it says that some packages are missing, when I write "npm fund" it gives me the following, I attach a screenshot, is it supposed to be like this?
![image](https://user-images.githubusercontent.com/72270982/163434232-8cf98e38-6a54-499b-b7c0-ff65b23240cc.png)

**Comment by BeepIsla** [comment]
fund != found. Look up what the words actually mean, nothing went wrong here.

**Comment by hammerx1337** [comment]
sorry, I already understood what was meant and wanted to delete this post, but I have the following problem, when I write node index.js STEAMWORKS I get this error
![image](https://user-images.githubusercontent.com/72270982/163434905-79a44889-5e9c-469e-8997-0c9a21d780b5.png)

**Comment by BeepIsla** [comment]
Run `npm i ./extension/steam`

**Comment by hammerx1337** [comment]
I tried but it still gives an error

**Comment by BeepIsla** [comment]
What error?

**Comment by hammerx1337** [comment]
same as in the screenshot

**Comment by BeepIsla** [comment]
That is impossible. They do different things.

**Comment by hammerx1337** [comment]
I don't know, maybe the node js additional tools were installed incorrectly, please tell me how to remove them completely and reinstall?

**Comment by hammerx1337** [comment]
I tried in different ways but still some traces remain in the system

**Comment by BeepIsla** [comment]
Manually running `npm i ./extension/steam` will try to build and install the module, if something goes wrong it will give details as to what went wrong

**Comment by hammerx1337** [comment]
still same error, tried everything
