### ISSUE TITLE
csgo overwatch bot master

### ISSUE THREAD

**Issue by SeeYoo64** [BeepIsla/CSGO-Overwatch-Bot#28]
Im open command propt, then i should write - npm i, when im wrote this, im see error. - 
Cannot read property 'resolve' of undefined.
I cannot do with this anything. Help me

**Comment by BeepIsla** [comment]
Screenshot

**Comment by SeeYoo64** [comment]
![image](https://user-images.githubusercontent.com/63878663/79660944-d5431700-81bc-11ea-9fba-63aa1a35ad53.png)

**Comment by BeepIsla** [comment]
Uninstall NodeJS and NPM (Google how to), then reinstall them. Your installation is broken.

**Comment by SeeYoo64** [comment]
thanks, issue
