### ISSUE TITLE
Are downloaded demos automatically deleted?

### ISSUE THREAD

**Issue by GabrielBigardi** [BeepIsla/CSGO-Overwatch-Bot#31]
Hello, i'm currently running the program in a VPS with limited HDD, and i cant find anywhere in the code something telling if the downloaded cases are automatically deleted, and i want to know that, please...

**Comment by BeepIsla** [comment]
As per README:

- `verdict`
- - `writeLog`: Should we write logs to a file?
- - `backupDemo`: Should we backup the demo file?

If you don't want to save demos set `backupDemo` to false, same with logs `writeLog`.
