### ISSUE TITLE
Error when running index

### ISSUE THREAD

**Issue by OFFLYNE** [BeepIsla/CSGO-Overwatch-Bot#35]
Requested Overwatch case
Downloading case 3412854513176936782 from url http://replay233.wmsj.cn/730/003412791911881114259_0611951431.dem.bz2
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 121.46.225.10:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (C:\Users\XXXXXX\Desktop\CSGO-Overwatch-Bot-master\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '121.46.225.10',
  port: 80
}
PS C:\Users\XXXXXX\Desktop\CSGO-Overwatch-Bot-master>

**Comment by OFFLYNE** [comment]
Every time i get this error it's a chinese link (.cn)

**Comment by BeepIsla** [comment]
Can you download the file manually in your browser?

**Comment by OFFLYNE** [comment]
i can do

> Can you download the file manually in your browser? I can download the demo just fine over browser and via NodeJS, the same way the Overwatch Bot does it.

![2234fb2da0bdee1940f48615347c86d8](https://user-images.githubusercontent.com/46251448/81762317-a292f280-94cc-11ea-89fc-fbfec1cc9abd.png)

**Comment by BeepIsla** [comment]
Either you have a redirect in your `hosts` file or China seems to be blocking your IP for some reason, are you using a VPN or Proxy?

**Comment by OFFLYNE** [comment]
> Either you have a redirect in your `hosts` file or China seems to be blocking your IP for some reason, are you using a VPN or Proxy?

I dont use any proxy or vpn

**Comment by BeepIsla** [comment]
Closing due to it being an issue which seems to be specific to you and your connection to Chinese download servers. I can't help you with this.
