### ISSUE TITLE
A request failed to run. Github, Steam or CSGO might currently be offline

### ISSUE THREAD

**Issue by fhersone** [BeepIsla/CSGO-Overwatch-Bot#40]
happens after 3-4 cases forcing me to restart the script?

**Comment by BeepIsla** [comment]
When exactly does this happen? What is the last message you see before this happens?

**Comment by fhersone** [comment]
Waiting 234.89 seconds to avoid the GC ignoring us 
after this next message is the offline thing

ive rerun the program with steam closed now maybe that will work i will get back to you as soon as possible ( next 20 min)

**Comment by BeepIsla** [comment]
Its possible if you start a game it kicks the bot out of its play-session.

**Comment by fhersone** [comment]
when i've ran the program i only had steam opened without the game running

**Comment by fhersone** [comment]
i'm currently running it now and waiting if the msg pops up again which it has twice now and will let you know and send u a SS of what it says

**Comment by BeepIsla** [comment]
Released version 2.0 - This might be fixed or not, re-open if not fixed.
