### ISSUE TITLE
Possible to run it on two accounts?

### ISSUE THREAD

**Issue by OscarLam1337** [BeepIsla/CSGO-Overwatch-Bot#42]
Is it possible to run the node two times on the same PC but of course with two clones for two accounts?

Like I have two clones of it and then start the one with a other config on my smurf 1.
And the other clone with a other config on my smurf 2 on the same PC.

**Comment by BeepIsla** [comment]
Clone the folder, one folder is account1, other folder is account2

**Comment by OscarLam1337** [comment]
So it is possible without any issues?

**Comment by BeepIsla** [comment]
Yes, there is no reason why this wouldn't work.
