### ISSUE TITLE
Does it trigger VAC?

### ISSUE THREAD

**Issue by OscarLam1337** [BeepIsla/CSGO-Overwatch-Bot#43]
Will this stuff trigger VAC in any way?
Or is it completely safe.

**Comment by BeepIsla** [comment]
VAC is not even loaded while you use this, so no: Automated VAC bans will not happen. But if Valve catches you use it they might disable your account or manually ban you.

**Comment by OscarLam1337** [comment]
How could they catch me ?

**Comment by BeepIsla** [comment]
I don't know, Valve magic. They could check activity or patterns, maybe there are automated system in place but nobody knows.

**Comment by OscarLam1337** [comment]
Well are there any reports yet?

**Comment by BeepIsla** [comment]
I know of one person who got two of their accounts disabled, one of the reasons given by Steam Support was "Automating Overwatch cases". This was during the time when someone else used thousands of accounts in Overwatch to ban anyone they want, so Valve cracked down on all of it pretty fast. That's all I know.

**Comment by OscarLam1337** [comment]
How long ago was that?

**Comment by BeepIsla** [comment]
I don't remember, a few months ago. 5+ months.

**Comment by OscarLam1337** [comment]
Well I guess nothing else happened since then.
Hope its safe.
