### ISSUE TITLE
Quick question about updates

### ISSUE THREAD

**Issue by OscarLam1337** [BeepIsla/CSGO-Overwatch-Bot#48]
I saw that the websocket-extensions got updated.
Do I need to redownload anything to update it?
Or incase there is an update what should I do?

**Comment by BeepIsla** [comment]
Download, extract, run `npm ci` (Basically same as `npm install`), make sure your config is up-to-date and does not have any values missing, done.

**Comment by OscarLam1337** [comment]
So I should extract in the same folder right?

**Comment by BeepIsla** [comment]
yes
