### ISSUE TITLE
can't download the 13th case

### ISSUE THREAD

**Issue by crx9** [BeepIsla/CSGO-Overwatch-Bot#49]
Done parsing case 3417634027945853425
Waiting 236.234 seconds to avoid the GC ignoring us
Suspect has not been banned yet according to the Steam API
Internal ID: 12
CaseID: 3417634027945853425
Suspect: 76561199049462300
Infractions:
        Aimbot: 0
        Wallhack: 1
        TeamKills: 0
        TeamDamage: 0
        Other: 0
        Griefing: 0
        Reported: No
        Already convicted: No
Timings:
        Total: 308s
        Download: 60s
        Unpacking: 3s
        Parsing: 3s
        Throttle: 179s
--------------------
Requested Overwatch case
Downloading case 3417633149625041543 from url http://replay187.valve.net/730/003417621080766939522_0993544864.dem.bz2

13th case always cant be downloaded,I tried many times but it happends every times
the  file is  0kb.

**Comment by BeepIsla** [comment]
I don't know why this happens.
