### ISSUE TITLE
"Killed"

### ISSUE THREAD

**Issue by greg-droid** [BeepIsla/CSGO-Overwatch-Bot#51]
After setting up the ow bot, it is able to log into my account and get CS:GO stats. The bot is able to request and download a case. After unpacking the task gets killed. 

I am running the program on ubuntu-18.04-x86_64

I am not good at stuff like this, so I am probably doing something wrong, does anyone know what that might be?
![3aa885ebfed7f9a88144d0ac86fc4049](https://user-images.githubusercontent.com/67144339/85114135-c3abd900-b218-11ea-9f33-0b6306cb0f57.png)

EDIT:
Running the program on windows works fine, but I would like to be able to run it on ubuntu.
![f46769b611a2613449ff7c173a38b309](https://user-images.githubusercontent.com/67144339/85114483-a297b800-b219-11ea-8b71-7ebeb0c6f152.png)

**Comment by BeepIsla** [comment]
I don't really know what the problem could be, maybe NodeJS is running out of ram? Check if there are any logs generated by Node in your folder.

**Comment by greg-droid** [comment]
Ill try giving more ram, the program was only using about 50% but that could be the problem

**Comment by greg-droid** [comment]
> I don't really know what the problem could be, maybe NodeJS is running out of ram? Check if there are any logs generated by Node in your folder.

This was the problem. The program was using more ram than i was giving it.
