### ISSUE TITLE
The bot doesnt work!

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/CSGO-Overwatch-Bot#60]
Checking protobufs...
Found protobufs
Checking for updates...
Up to date!
Establishing CSGO GameCoordinator connection...
A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...

I'm completely offline on steam so there's a bug or sth

**Comment by BeepIsla** [comment]
Are you having CSGO open at the same time on the same acccount?

**Comment by ZAp220** [comment]
No, I tried to close Csgo, Steam , just to make sure that everything is offline.
Nothing happened, still giving that message.

**Comment by BeepIsla** [comment]
What is your config?

**Comment by ZAp220** [comment]
{
	"account": {
		"username": "xxxxxxxxxxx",
		"password": "xxxxxxxxxxxxxx",
		"sharedSecret": ""
	},
	"parsing": {
		"steamWebAPIKey": "xxxxxxxxxxxxxxxxxxxxxxx",
		"minimumTime": 240,
		"aimbot": {
			"maxTicks": 10,
			"threshold": 1.0
		},
		"afking": {
			"radius": 80
		}
	},
	"verdict": {
		"writeLog": true,
		"backupDemo": false,
		"maxVerdicts": 0,
		"maxAimbot": 10,
		"maxWallKills": 7,
		"maxTeamKills": 1,
		"maxTeamDamage": 180,
		"maxAFKing": 3
	},
	"richPresence": {
		"steam_display": "#display_overwatch"
	}
}

**Comment by BeepIsla** [comment]
I can't see anything wrong with this, it must be a problem on your side because it works perfectly fine for me. I just tried it on a fresh install.

**Comment by ZAp220** [comment]
What about if you try with teamviewer on my PC maybe you can solve sth.

**Comment by BeepIsla** [comment]
No
