### ISSUE TITLE
Banned ?

### ISSUE THREAD

**Issue by vyeeechor** [BeepIsla/CSGO-Overwatch-Bot#63]
I can banned for using this?

**Comment by BeepIsla** [comment]
If Valve catches you and manually bans you: Yes. They do not want players automating Overwatch.

**Comment by vyeeechor** [comment]
Chance to manual ban??

**Comment by BeepIsla** [comment]
50/50. Either it happens or it doesn't.

**Comment by vyeeechor** [comment]
Lasy question 

You have banned for using this script ??

**Comment by BeepIsla** [comment]
No, I don't use it. I know of another person who has been banned for using it on like 4 accounts roughly a year ago or so.

**Comment by vyeeechor** [comment]
its a vac ban on game ban ?

**Comment by BeepIsla** [comment]
Your account will get disabled and you cannot access it anymore

**Comment by vyeeechor** [comment]
i used the script once, i have to worry about the account ??

**Comment by BeepIsla** [comment]
No

**Comment by bg1337** [comment]
I think you might get your account disabled if you forced verdicts the suspects or if you played with the config, i recommend you keep it as it and don't touch the verdict settings..
