### ISSUE TITLE
Automatic Reply

### ISSUE THREAD

**Issue by chmosama** [BeepIsla/CSGO-Overwatch-Bot#67]
I've been trying to add automatic reply functionality and It's almost done but I am facing one little problem with the sender name.
I cannot set the sender's name before printing it in the console.
Here's the code:
`async function automaticMsg(){`
`	let friendName;`
`	steamUser.on("friendMessage", function (steamID, message) {`
`		//StartWebAPI`
`		if (config.parsing.steamWebAPIKey && config.parsing.steamWebAPIKey.length >= 10) {`
`			request("https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=" + config.parsing.steamWebAPIKey + "&format=json&steamids=" + steamID + "", { json: true }, (err, res, body) => {`
`				if (err) { return console.log(err); }`
`				var json = JSON.stringify(body);`
`				var jsonParsed = JSON.parse(json);`
`				friendName = jsonParsed.response.players[0].personaname;`
`				console.log("Sender: " + friendName);`
`			});`
`		}`
`		//EndWebAPI`
`		steamUser.messageReceived = {};`
`		console.log("[" + steamUser.accountInfo.name + "] Message from " + friendName + ": " + message);`
`		if (!this.messageReceived[steamID]) {`
`			steamUser.chatMessage(steamID, "[Automatic Message] I'm busy with automatic OverwatchBot.");`
`			this.messageReceived[steamID] = true;`
`		}`
`	});`
`}`

Then I just call this function before :
`doOverwatchCase();`

But the problem is with the variable name `friendName` It is not setting the value first time when someone sends a message and prints the first message with the `undefined` sender name.
Can you look into this :)

![Screenshot_223](https://user-images.githubusercontent.com/7778119/88548517-a39ddf80-d038-11ea-930c-f66caff02124.png)

![Screenshot_224](https://user-images.githubusercontent.com/7778119/88548684-dd6ee600-d038-11ea-9a53-2cad47bfdc24.png)

**Comment by BeepIsla** [comment]
How is this related to **my** Overwatch bot? If you edit this script you are on your own. Do not come to me for help.

**Comment by chmosama** [comment]
[Update] Instead of using Steam API, I was able to use the existing node steam-user module to figure it out with fewer code lines 👍 
Code:
`async function automaticMsg(){`
`	steamUser.on("friendMessage", function (steamID, message) {`
`		steamUser.messageReceived = {};`
`		if (!this.messageReceived[steamID]) {`
`			steamUser.getPersonas([steamID], function(err, personas) {`
`				if (err) {`
`					console.log('error.')`
`				} else {`
`					var persona = personas[steamID.getSteamID64()];`
`					var name = persona ? persona.player_name : ("[" + steamID.getSteamID64() + "]");`
`					steamUser.chatMessage(steamID,"Hi " + name + ", " + config.parsing.customMessage);`
`					console.log("[" + steamUser.accountInfo.name + "] Message from " + name + ": " + message);`
`				}`
`			});`
`			this.messageReceived[steamID] = true;`
`		}`
`	});`
`}`
and in the config.json:
`"steamWebAPIKey": "XXXXXXXXXXXXXXXX",`
`"customMessage": "Testing",`

I would love to see this implement in your next release. Thanks.
