### ISSUE TITLE
Error: getaddrinfo ENOENT raw.githubusercontent.com

### ISSUE THREAD

**Issue by GIGIGIVEVEH** [BeepIsla/CSGO-Overwatch-Bot#68]
excuse me,but i got a problem.
-------------------------------------------------------------------------------------------
C:\Users\ad\Desktop\RP16\CSGO-Overwatch-Bot-master>node index.js
Successfully logged into 765xxx9844xxxx200
Checking protobufs...
Found protobufs
Checking for updates...
Error: getaddrinfo ENOENT raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com'
}
A new version is available on Github @ https://github.com/BeepIsla/CSGO-Overwatch-Bot
Downloading is optional but recommended. Make sure to check if there are any new values to be added in your old "config.json"
Establishing CSGO GameCoordinator connection...
A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...
-------------------------------------------------------------------------------------------
thats what i got, im not running csgo or steam client, and the vpn is set to USA. can u tell me how to fix it? and thank u very much for ur good release.

**Comment by BeepIsla** [comment]
First error indicates something is blocking you from accessing [this](https://raw.githubusercontent.com/BeepIsla/CSGO-Overwatch-Bot/master/package.json) URL.

Second error indicates something failed when logging into Steam, your VPN is likely being blocked.

**Comment by GIGIGIVEVEH** [comment]
> First error indicates something is blocking you from accessing [this](https://raw.githubusercontent.com/BeepIsla/CSGO-Overwatch-Bot/master/package.json) URL.
> 
> Second error indicates something failed when logging into Steam, your VPN is likely being blocked.


thank u sir
