### ISSUE TITLE
"ETIMEDOUT" after update 8/17/2020

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/CSGO-Overwatch-Bot#71]
title^
after 2 case (and on vps it does the same)
![Screenshot_1](https://user-images.githubusercontent.com/45514952/90646342-c8ecca80-e23f-11ea-960f-17f68b10eb1a.png)

**Comment by BeepIsla** [comment]
China demo, does this happen on non-china demos too?

**Comment by xSuspect** [comment]
> China demo, does this happen on non-china demos too?
it happens but rarely, I keep more on a vps

**Comment by xSuspect** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/45514952/91216587-e4b00f00-e71e-11ea-87c8-0dbb50626388.png)
spam console,
and if if I leave it on a vps, it works, 1-2 hours after the above update, not like before 24-24 can it be fixed?
