### ISSUE TITLE
I Got This Error While Using The Overwatch Bot

### ISSUE THREAD

**Issue by MaRk5man5** [BeepIsla/CSGO-Overwatch-Bot#77]
![Screenshot (4)](https://user-images.githubusercontent.com/67968208/91160821-83207e00-e6e7-11ea-8c70-9208b71c2e4b.png)

This Error Came Many Times But Now Its Permanent Any Fixes Please Help.

**Comment by BeepIsla** [comment]
China demos have issues for some reason, there is no fix at the current moment, there are many other issues with the exact same problem.
