### ISSUE TITLE
I'm Getting This Error On The Updated Overwatch Bot

### ISSUE THREAD

**Issue by MaRk5man5** [BeepIsla/CSGO-Overwatch-Bot#85]
![Screenshot (12)](https://user-images.githubusercontent.com/67968208/91577511-7067ac80-e966-11ea-8ffd-d17ecd00df45.png)

**Comment by BeepIsla** [comment]
Update again and test if that fixes it.

**Comment by MaRk5man5** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/67968208/91578323-9b9ecb80-e967-11ea-8f15-3d9c94bcb75a.png)
It Just Lead To This New Error

**Comment by BeepIsla** [comment]
Apologies, one more time update and try again

**Comment by BeepIsla** [comment]
Confirmed working by #86
