### ISSUE TITLE
Doesn't work after update

### ISSUE THREAD

**Issue by ZAp220** [BeepIsla/CSGO-Overwatch-Bot#86]
https://prnt.sc/u7kfz0
I think the web api key is missing from the config or is it work even without ?

**Comment by BeepIsla** [comment]
Download and try again. API Key is not needed.

**Comment by PenguinSK** [comment]
It doesnt work, same error 

![image](https://user-images.githubusercontent.com/29003010/91584728-638d8d80-e953-11ea-89b0-967c70ea6745.png)

**Comment by BeepIsla** [comment]
Works here, did you update properly? Delete old files, download again, replace with new files.

**Comment by PenguinSK** [comment]
Yes, its working now.
