### ISSUE TITLE
Disconnected From steam With Eresult and message no connection

### ISSUE THREAD

**Issue by MaRk5man5** [BeepIsla/CSGO-Overwatch-Bot#87]
![Screenshot (15)](https://user-images.githubusercontent.com/67968208/91585934-5af87f80-e972-11ea-846a-f8e7e36be412.png)
This New Error Just Came 2 Times

**Comment by BeepIsla** [comment]
Not an error, your config wants 1 case, you did that one case and the bot logs off. Read the README.

> `maxVerdicts`: Maximum amount of Overwatch cases to do before stopping. `0` for unlimited.
