### ISSUE TITLE
[QUESTION] Anti Aim Detector

### ISSUE THREAD

**Issue by BlackYuzia** [BeepIsla/CSGO-Overwatch-Bot#90]
I was tested a **AA** detector on my "Rage Player", your version of this detector say what he **do not** use **AA**.
When I test with my own version (before you create 2.0), this guy get more like 20 detects.

I can be think AA detects can be added to aimbot detects, but logs say `this user didn't have any AA detects`, so ...
```
		"AntiAim": {
			"result": {
				"aimbot": false,
				"wallhack": false,
				"speedhack": false,
				"teamharm": false
			},
			"raw": []
		},
```

![image](https://user-images.githubusercontent.com/25010528/91595056-92176280-e96b-11ea-9a30-877f3462bcd6.png)

Something wrong or what?
I can give you my demo for tests, if you want.

**Comment by BeepIsla** [comment]
On another demo I tried it on as soon as I made it not trigger during the round reset the AntiAim jumped to 0, I didn't test it on a rage cheater though. A demo download would be great.

**Comment by BlackYuzia** [comment]
@BeepIsla `https://dropmefiles.com/YJLyU`
**HvH Boy** with nickname **13v31**

**Comment by BeepIsla** [comment]
![image](https://user-images.githubusercontent.com/22947557/91612419-acf2d280-e97d-11ea-95fa-12d0b3b074bc.png)

**Comment by code-bye** [comment]
> ![image](https://user-images.githubusercontent.com/22947557/91612419-acf2d280-e97d-11ea-95fa-12d0b3b074bc.png)

(off topic) What font are you using on your console?

**Comment by BlackYuzia** [comment]
offtop

> (off topic) What font are you using on your console? @BeepIsla

@code-bye it is kinda **VS Code**. But I can be wrong.

**Comment by BlackYuzia** [comment]
> Seems to be fine here.

@BeepIsla hmm, `AA: 0` it is fine? :thinking: 
Or you didn't check my demo what I gave you?

**Comment by BeepIsla** [comment]
Oh lol, I think I looked at Aimbot instead of AntiAim, yeah its wrong.

**Comment by BlackYuzia** [comment]
@BeepIsla try to use my first version of AA detector.

**Comment by BeepIsla** [comment]
I added a check to make sure the AA detector doesn't run between rounds so it doesn't false-trigger for respawning players. This seems to have either broken it or it never worked in the first place.

When I remove the check here https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/ba2112f299e57909e3a8fa8a73689ffec9908595/detectors/AntiAim.js#L49 it ends up with 56 AA infractions.

**Comment by BlackYuzia** [comment]
So, @BeepIsla this issue has been **resolved**?

**Comment by BeepIsla** [comment]
I have no idea. I changed nothing regarding AA ever since (I think) yet apparently it sometimes outputs 300+ detections and sometimes (most of the time?) 0?

**Comment by BlackYuzia** [comment]
@BeepIsla what a check `this.isActiveRound`?

After removing this check I get 56 detects in rage demo what I have.

**Comment by BlackYuzia** [comment]
I found what all detects I get only when round is not active :eyes:

**Comment by BlackYuzia** [comment]
Hmm. If I right. You manualy check if round is end or round freeze has been start/end.
I think this check is useless for AA.

1. **AA can be active after round end** (yep). 
2. AA does not work while round is freeze (because angles of players are freezed too). 
_So we didn't get false-positive results._

**Comment by BeepIsla** [comment]
Its suppose to disable the AA check between rounds for respawning players. If AA is active post round or freeze time doesn't matter. If they are using AA any other time during the round should trigger an infraction.

**Comment by BlackYuzia** [comment]
> This is important because when spawning your lower body will be towards 0 degrees while your head wont be, it will result in a big difference and trigger an infraction.

Hmm. I didn't get false positive.
If you give me 3 types of demos (legit, rage, no cheats) I can optimize AA detector. 

About bug on spawn with lower body ... I think I didn't get false positive because I check too high degrees ... or maybe not :eyes: 
Need more tests with that.

What about remove this check now after that just wait what told users of that script/bot. Maybe they say "all is good" :eyes:

**Comment by BlackYuzia** [comment]
<details>
  <summary>Some info about AA Detector and etc</summary>

I spend some time for tests.
In cheat forums I saw what deg in cheaters is greater or equal like 35.

I setup more like 35 (40), but in my rage demo AA detects didn't decreased or something like that (**56**).

Current AA Detector can detect only AA what look at floor (0 deg or look at legs etc)

```
		if (
                lbyDelta <= 40 // Note #1
               || this.parent.suspectPlayer.eyeAngles.pitch !== 0  // Note #2 
			// All good
			return;
		}
```

> **Note 1:** This check if deg is normal, if deg is <= 40 this moment is not suspect because only cheaters can have deg diff >= 35 (40)

> **Note 2:** This check stop detect if current user look at forward, up or else angle. What this means? If AA look at UP (in to sky) we didn't detect this AA.

If I has been remove check for pitch angles ( ` this.parent.suspectPlayer.eyeAngles.pitch ` ) we can get false positive or something like this. I think.

When I check myself (I 100% don't use AA in this moment) I get this:
![image](https://user-images.githubusercontent.com/25010528/95003502-92e58900-05e8-11eb-8c8f-59700a66cdf3.png)

(LOL) ~~228~~ 224 false-positive detects without `this.parent.suspectPlayer.eyeAngles.pitch ` check.

So, using `this.parent.suspectPlayer.eyeAngles.pitch ` the only one way to correct detect AA in rage cheaters. Maybe exist any else ways and maybe he will be better. But I am too lazy for trying to find better ways.

**Also IDK what about legit AA.**
**Legit AA** can look at any **pitch** angles (up, down, forwart, backward etc)

Need more info about legit AA I think :thinking: 

Also I want saw RCS Detect. I think this is one of the best one detectors what we can do ... if we do this of course....
</details>

**Short info about spoiler info: AA Detector have many restrictions and too broken currently...**

**Comment by BlackYuzia** [comment]
Close because possibly fixed
