### ISSUE TITLE
Infractions numbers are wrong?

### ISSUE THREAD

**Issue by Borlax2** [BeepIsla/CSGO-Overwatch-Bot#91]
Hi,

the results are different from the overwatch case compared when analyzing it manually using force.js

and why there is a question marks next to the verdicts.

https://i.imgur.com/yC4zubH.png

https://i.imgur.com/sa8ddyt.png

Demo link: http://replay145.valve.net/730/003433007032305713554_1519774866.dem.bz2
Suspect: 76561199033116058

**Comment by Borlax2** [comment]
I tried to log the verdict results to see what's going on:

https://i.imgur.com/0kiBrdH.png
+
https://i.imgur.com/Nro14nh.png

I assume false means "not cheating" or "skipping verdict"
even though the target is cheating and here are the results from the force.js:
https://i.imgur.com/Pwty3kl.png

**Comment by xSuspect** [comment]
https://prnt.sc/u7nngu

**Comment by BeepIsla** [comment]
The question marks are caused by unicode not being supported for ticks and crosses. See https://github.com/BeepIsla/CSGO-Overwatch-Bot/blob/cc84db135c82d1d1a5f9d7a72814bf943f7c7d74/helpers/Demo.js#L83

**Comment by xSuspect** [comment]
@BeepIsla 
![FDGDGDFG](https://user-images.githubusercontent.com/45514952/91606218-5afc7d80-e97a-11ea-8fe2-3678569f05eb.png)
I haven't created a new topic, how do I solve it?

**Comment by xSuspect** [comment]
![werwrw](https://user-images.githubusercontent.com/45514952/91606865-9ba8c680-e97b-11ea-9a3e-a8e49c4c6f85.png)
("maxVerdicts": 35,)

**Comment by BeepIsla** [comment]
@xSuspect make your own thread about a different issue, don't hijack existing ones.

This has been fixed, update and try again.

**Comment by BeepIsla** [comment]
This should now be fixed. Update and try again. Reopen if it still does not work.
