### ISSUE TITLE
Disconnected from Steam with EResult 3 and message NoConnection

### ISSUE THREAD

**Issue by marki07** [BeepIsla/CSGO-Overwatch-Bot#95]
Disconnected from Steam with EResult 3 and message NoConnection this error is poping up if i let launch it.

**Comment by BeepIsla** [comment]
Read. The. Readme. #87

**Comment by marki07** [comment]
what should i find there?

**Comment by BeepIsla** [comment]
> `maxVerdicts`: Maximum amount of Overwatch cases to do before stopping. `0` for unlimited.

Its the reason why the bot disconnects, one case is finished and it stops.
