### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PenguinSK** [BeepIsla/CSGO-Overwatch-Bot#99]
I have this error every time after it finished first ow case, already tried redownload and still same.

![image](https://user-images.githubusercontent.com/29003010/91635126-0f87b500-e9f6-11ea-9af9-84f4db1b4c79.png)

**Comment by BeepIsla** [comment]
This has been fixed already, are you sure you deleted all old files and downloaded it again?

**Comment by PenguinSK** [comment]
Ye, I dowloaded it again few times and it works
